### ISSUE TITLE
Updating a PR should not throw an exception

### ISSUE THREAD

**Issue by kiranbayram** [scala-steward-org/scala-steward#1393]
`process.slurp` throws an exception in some cases (see stacktrace below), this shouldn't be the case

```
[2020-04-02T13:42:29.260Z] 2020-04-02 13:42:29,083 INFO  Process update org.scala-sbt:sbt : 1.3.8 -> 1.3.9
[2020-04-02T13:42:29.644Z] 2020-04-02 13:42:29,444 INFO  Found PR https://github.com/AutoScout24/XXX/pull/123
[2020-04-02T13:42:29.644Z] 2020-04-02 13:42:29,529 INFO  PR update strategy is set to always
[2020-04-02T13:42:29.644Z] 2020-04-02 13:42:29,529 INFO  Merge branch 'master' into update/sbt-1.3.9 and apply again
[2020-04-02T13:42:29.971Z] java.io.IOException: 'git checkout master' exited with code 1
[2020-04-02T13:42:29.971Z] error: you need to resolve your current index first
[2020-04-02T13:42:29.971Z] csv-to-json/project/build.properties: needs merge
[2020-04-02T13:42:29.971Z] 
[2020-04-02T13:42:29.971Z]     at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:48)
[2020-04-02T13:42:29.971Z]     at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:44)
```

**Comment by kiranbayram** [comment]
I'm looking into this

**Comment by kiranbayram** [comment]
I see in the logs
```
CONFLICT (modify/delete): some-file deleted in master and modified in HEAD. Version HEAD of some-file left in tree.
```

It looks like this happens when a modified file is deleted on master

**Comment by kiranbayram** [comment]
I think i was able to reproduce the issue in tests on https://github.com/kiranbayram/scala-steward/tree/issue-1393 branch

**Comment by kiranbayram** [comment]
I unfortunately couldn't find a git command which would successfully do the merge in this case :(
