### ISSUE TITLE
Run in Docker fails due to firejail with `--disable-sandbox`

### ISSUE THREAD

**Issue by avdv** [scala-steward-org/scala-steward#1727]
Hi.

We are running scala-steward weekly within our team using the Docker image. Last monday, this went fine:
```
sha256:08f6ffa4769fc0f6e421c8f9b653ea61c2db06f2a74cbc4fa31cc035bef210e6 for fthomas/scala-steward:latest with digest docker.io/fthomas/scala-steward@sha256:2d4c2feca26d1c002a114f235800f8536946db9f9442e1fd6bb339a7cbe2bb1b ...
```

But today, there was this error:

```
Using docker image sha256:3f3513281e8d6d2762c72d54dabc6b5ba1da3e5af63f62958f7eddc19e3888f2 for fthomas/scala-steward:latest with digest docker.io/fthomas/scala-steward@sha256:65018aaa772bb2b7c5f4e20b0495edd239e027f7941a8fcb82696d611b229314 ...
...
java.io.IOException: Cannot run program "firejail" (in directory "/builds/genesis/updates/workspace/repos/genesis/eve-core"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.scalasteward.core.io.process$.$anonfun$createProcess$1(process.scala:78)
	at flatMap @ org.scalasteward.core.io.process$.slurp(process.scala:43)
	at ifM$extension @ io.chrisdavenport.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.info(Slf4jLoggerInternal.scala:76)
	at $greater$greater$extension @ org.scalasteward.core.scalafix.MigrationsLoader.loadMigrations(MigrationsLoader.scala:43)
	at flatMap @ org.scalasteward.core.buildtool.sbt.SbtAlg$$anon$1.$anonfun$getDependencies$1(SbtAlg.scala:82)
	at flatMap @ org.scalasteward.core.buildtool.sbt.SbtAlg$$anon$1.getDependencies(SbtAlg.scala:80)
	at flatTraverse @ org.scalasteward.core.scalafix.MigrationsLoader.loadAll(MigrationsLoader.scala:38)
	at flatTraverse @ org.scalasteward.core.scalafix.MigrationsLoader.loadAll(MigrationsLoader.scala:38)
	at flatTraverse @ org.scalasteward.core.scalafix.MigrationsLoader.loadAll(MigrationsLoader.scala:38)
	at flatTraverse @ org.scalasteward.core.scalafix.MigrationsLoader.loadAll(MigrationsLoader.scala:38)
	at flatMap @ org.scalasteward.core.buildtool.sbt.SbtAlg$$anon$1.containsBuild(SbtAlg.scala:69)
	at flatSequence @ org.scalasteward.core.update.ArtifactMigrations$.create(ArtifactMigrations.scala:51)
	at flatMap @ org.scalasteward.core.buildtool.mill.MillAlg$$anon$1.containsBuild(MillAlg.scala:52)
	at flatSequence @ org.scalasteward.core.update.ArtifactMigrations$.create(ArtifactMigrations.scala:51)
```

We already use `--disable-sandbox`:

```
/opt/docker/bin/scala-steward \
  --disable-sandbox \
  --workspace  "$STEWARD_DIR/workspace" \
  --process-timeout 30min \
  --do-not-fork \
  --repos-file "$STEWARD_DIR/repos.md" \
  --default-repo-conf "$STEWARD_DIR/default.scala-steward.conf" \
  --git-author-email ${EMAIL} \
  --vcs-type "gitlab" \
  --vcs-api-host "${CI_API_V4_URL}" \
  --vcs-login "${LOGIN}" \
  --git-ask-pass "$STEWARD_DIR/askpass.sh"
```

**Comment by avdv** [comment]
Oh, that was probably fixed by 75d6bd93d791545a1b0afe373e8d775619776d0d already...

**Comment by fthomas** [comment]
Yes, I think so. You also can remove the `--disable-sandbox` option now.

**Comment by avdv** [comment]
Bad timing... ;-)

Closing, thanks!
