### ISSUE TITLE
Error after upgrade to sbt 1.4.x

### ISSUE THREAD

**Issue by Philippus** [scala-steward-org/scala-steward#1814]
After upgrading sbt to 1.4.4 in a project I can no longer run scala-steward successfully. I'm getting the error below of a run on `v0.8.1-121-145f3481-SNAPSHOT`. Any clue what might be going on?:

```
2020-12-18 11:52:21,621 ERROR Steward *** failed
java.io.IOException: 'BINTRAY_USER=*** BINTRAY_PASS=*** BLAZE_ARTIFACTORY_USER=*** BLAZE_ARTIFACTORY_PASSWORD=*** sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 2
	at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:54)
	at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:50)
	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
	at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:245)
	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
	at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:244)
	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
	at flatMap @ fs2.internal.CompileScope.$anonfun$close$2(CompileScope.scala:242)
	at flatMap @ fs2.internal.CompileScope.close(CompileScope.scala:241)
	at main$ @ org.scalasteward.core.Main$.main(Main.scala:22)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
	at flatMap @ fs2.internal.CompileScope.$anonfun$openAncestor$2(CompileScope.scala:261)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$17(Algebra.scala:545)
	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
	at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:245)
	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
	at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:244)
```

**Comment by fthomas** [comment]
I've no immediate idea what's going wrong here. Normally Scala Steward includes the output of the command in its exception and it seems that `sbt` exited here without printing anything to stdout.

**Comment by Philippus** [comment]
Ok, thank you. I tried the `sbt stage`-way of running scala-steward instead of docker, and that's running ok. Not sure if that is helpful information, there's still quite a bit of moving parts I guess, like coursier/docker/git.

**Comment by ryh-cc** [comment]
I believe I have a similar error (if not happy to open a new issue) 

```
2021-01-07 17:06:34,299 INFO  Refresh cache of ryh-cc/akka
2021-01-07 17:08:36,331 ERROR Steward ryh-cc/akka failed
java.io.IOException: 'sbt -batch -no-colors ;set offline := true;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 137
[info] [launcher] getting org.scala-sbt sbt 1.3.13  (this may take some time)...
downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.3.13/sbt-1.3.13.jar ...
:: loading settings :: url = jar:file:/opt/docker/sbt/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
        [SUCCESSFUL ] org.scala-sbt#sbt;1.3.13!sbt.jar (38ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.jar ...
        [SUCCESSFUL ] org.scala-lang#scala-library;2.12.10!scala-library.jar (485ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/main_2.12/1.3.13/main_2.12-1.3.13.jar ...
        [SUCCESSFUL ] org.scala-sbt#main_2.12;1.3.13!main_2.12.jar (241ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.3.4/io_2.12-1.3.4.jar ...
        [SUCCESSFUL ] org.scala-sbt#io_2.12;1.3.4!io_2.12.jar (73ms)
        
        <.......>
        : retrieving :: org.scala-sbt#boot-app
        confs: [default]
        81 artifacts copied, 0 already retrieved
[info] [launcher] getting Scala 2.12.10 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
        confs: [default]
        6 artifacts copied, 0 already retrieved
[info] welcome to sbt 1.3.13 (IcedTea Java 1.8.0_212)
[info] loading global plugins from /root/.sbt/1.0/plugins
[info] Compiling 1 Scala source to /root/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.10. Compiling...
[info]   Compilation completed in 6.661s.
[info] Done compiling.
[info] loading settings for project akka-build from plugins.sbt ...
[info] loading project definition from /var/scala-steward/workspace/repos/ryh-cc/akka/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Compiling 35 Scala sources to /var/scala-steward/workspace/repos/ryh-cc/akka/project/target/scala-2.12/sbt-1.0/classes ...
[info] Done compiling.
[info] loading settings for project akka from build.sbt ...
[info] resolving key references (50364 settings) ...
[info] set current project to akka (in build file:/var/scala-steward/workspace/repos/ryh-cc/akka/)
[info] Defining offline
[info] The new value will be used by updateConfiguration
[info] Reapplying settings...
[info] set current project to akka (in build file:/var/scala-steward/workspace/repos/ryh-cc/akka/)
[info] Setting Scala version to 2.12.11 on 41 projects.
[info] Reapplying settings...

        at org.scalasteward.core.io.process$.$anonfun$slurp$10(process.scala:49)
        at org.scalasteward.core.io.process$.$anonfun$slurp$10$adapted(process.scala:45)
        at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:216)
        at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:215)
        at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:191)
        at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:214)
        at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:191)
        at flatMap @ fs2.internal.CompileScope.$anonfun$close$2(CompileScope.scala:212)
        at flatMap @ fs2.internal.CompileScope.close(CompileScope.scala:211)
        at main$ @ org.scalasteward.core.Main$.main(Main.scala:22)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:414)
        at flatMap @ fs2.internal.CompileScope.$anonfun$openAncestor$2(CompileScope.scala:231)
        at flatMap @ fs2.internal.FreeC$.$anonfun$compile$15(Algebra.scala:517)
        at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:216)
        at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:215)
        at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:191)
        at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:214)
2021-01-07 17:08:36,345 INFO  ──────────── Total time: Steward ryh-cc/akka: 2m 2s 516ms ────────────
2021-01-07 17:08:36,359 INFO  ──────────── Total time: run: 4m 25s 727ms ────────────
```

**Comment by fthomas** [comment]
@ryh-cc That issue looks unrelated to the OP and more like a memory issue. Try tweaking the memory options for sbt as shown in https://github.com/scala-steward-org/scala-steward/issues/1437#issuecomment-650090709.

**Comment by atnoya** [comment]
I am having the same issue as the original message, I run it with DEBUG enabled:

```
2021-05-10 12:19:55,145 ERROR Steward xxxxxx failed
java.io.IOException: 'LOG_LEVEL=TRACE ARTIFACTORY_USERNAME=****** ARTIFACTORY_PASSWORD=****** SBT_OPTS=-Xmx7168m -Xss1024m -XX:MaxMetaspaceSize=512m sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 2
copying runtime jar...
[info] [launcher] getting org.scala-sbt sbt 1.4.9  (this may take some time)...
downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.4.9/sbt-1.4.9.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.4.0/io_2.12-1.4.0.jar ...
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.12/scala-library-2.12.12.jar ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/main_2.12/1.4.9/main_2.12-1.4.9.jar ...
:: loading settings :: url = jar:file:/usr/share/sbt/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/usr/share/sbt/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/usr/share/sbt/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/usr/share/sbt/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
	[SUCCESSFUL ] org.scala-sbt#sbt;1.4.9!sbt.jar (1881ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/logic_2.12/1.4.9/logic_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#io_2.12;1.4.0!io_2.12.jar (2394ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/actions_2.12/1.4.9/actions_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#logic_2.12;1.4.9!logic_2.12.jar (805ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/main-settings_2.12/1.4.9/main-settings_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#actions_2.12;1.4.9!actions_2.12.jar (859ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/run_2.12/1.4.9/run_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#main_2.12;1.4.9!main_2.12.jar (3406ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/command_2.12/1.4.9/command_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#main-settings_2.12;1.4.9!main-settings_2.12.jar (1279ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/collections_2.12/1.4.9/collections_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#run_2.12;1.4.9!run_2.12.jar (779ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/scripted-plugin_2.12/1.4.9/scripted-plugin_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#command_2.12;1.4.9!command_2.12.jar (901ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-lm-integration_2.12/1.4.9/zinc-lm-integration_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#scripted-plugin_2.12;1.4.9!scripted-plugin_2.12.jar (758ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-logging_2.12/1.4.9/util-logging_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#collections_2.12;1.4.9!collections_2.12.jar (960ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.3.0/scala-xml_2.12-1.3.0.jar ...
	[SUCCESSFUL ] org.scala-sbt#zinc-lm-integration_2.12;1.4.9!zinc-lm-integration_2.12.jar (780ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.1.6/launcher-interface-1.1.6.jar ...
	[SUCCESSFUL ] org.scala-sbt#util-logging_2.12;1.4.9!util-logging_2.12.jar (989ms)
downloading https://repo1.maven.org/maven2/com/github/ben-manes/caffeine/caffeine/2.8.5/caffeine-2.8.5.jar ...
	[SUCCESSFUL ] org.scala-sbt#launcher-interface;1.1.6!launcher-interface.jar (748ms)
downloading https://repo1.maven.org/maven2/io/get-coursier/lm-coursier-shaded_2.12/2.0.6/lm-coursier-shaded_2.12-2.0.6.jar ...
	[SUCCESSFUL ] org.scala-lang.modules#scala-xml_2.12;1.3.0!scala-xml_2.12.jar(bundle) (1047ms)
downloading https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar ...
	[SUCCESSFUL ] org.apache.logging.log4j#log4j-api;2.11.2!log4j-api.jar (901ms)
downloading https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar ...
	[SUCCESSFUL ] com.github.ben-manes.caffeine#caffeine;2.8.5!caffeine.jar (1420ms)
downloading https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-slf4j-impl/2.11.2/log4j-slf4j-impl-2.11.2.jar ...
	[SUCCESSFUL ] org.apache.logging.log4j#log4j-slf4j-impl;2.11.2!log4j-slf4j-impl.jar (793ms)
downloading https://repo1.maven.org/maven2/com/swoval/file-tree-views/2.1.6/file-tree-views-2.1.6.jar ...
	[SUCCESSFUL ] org.scala-lang#scala-library;2.12.12!scala-library.jar (8028ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-core_2.12/1.4.3/librarymanagement-core_2.12-1.4.3.jar ...
	[SUCCESSFUL ] io.get-coursier#lm-coursier-shaded_2.12;2.0.6!lm-coursier-shaded_2.12.jar (2495ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-ivy_2.12/1.4.3/librarymanagement-ivy_2.12-1.4.3.jar ...
	[SUCCESSFUL ] org.apache.logging.log4j#log4j-core;2.11.2!log4j-core.jar (1597ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.4.4/compiler-interface-1.4.4.jar ...
	[SUCCESSFUL ] org.scala-sbt#librarymanagement-core_2.12;1.4.3!librarymanagement-core_2.12.jar (492ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile_2.12/1.4.4/zinc-compile_2.12-1.4.4.jar ...
	[SUCCESSFUL ] org.scala-sbt#zinc-compile_2.12;1.4.4!zinc-compile_2.12.jar (185ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-relation_2.12/1.4.9/util-relation_2.12-1.4.9.jar ...
	[SUCCESSFUL ] com.swoval#file-tree-views;2.1.6!file-tree-views.jar (880ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-position_2.12/1.4.9/util-position_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#util-relation_2.12;1.4.9!util-relation_2.12.jar (182ms)
downloading https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-scalajson_2.12/0.9.1/sjson-new-scalajson_2.12-0.9.1.jar ...
	[SUCCESSFUL ] org.scala-sbt#util-position_2.12;1.4.9!util-position_2.12.jar (181ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.12/scala-reflect-2.12.12.jar ...
	[SUCCESSFUL ] org.scala-sbt#librarymanagement-ivy_2.12;1.4.3!librarymanagement-ivy_2.12.jar (874ms)
downloading https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.12/0.9.1/sjson-new-core_2.12-0.9.1.jar ...
	[SUCCESSFUL ] org.scala-sbt#compiler-interface;1.4.4!compiler-interface.jar (796ms)
downloading https://repo1.maven.org/maven2/com/eed3si9n/shaded-jawn-parser_2.12/0.9.1/shaded-jawn-parser_2.12-0.9.1.jar ...
	[SUCCESSFUL ] com.eed3si9n#sjson-new-scalajson_2.12;0.9.1!sjson-new-scalajson_2.12.jar (779ms)
downloading https://repo1.maven.org/maven2/com/eed3si9n/shaded-scalajson_2.12/1.0.0-M4/shaded-scalajson_2.12-1.0.0-M4.jar ...
	[SUCCESSFUL ] com.eed3si9n#shaded-jawn-parser_2.12;0.9.1!shaded-jawn-parser_2.12.jar (781ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/completion_2.12/1.4.9/completion_2.12-1.4.9.jar ...
	[SUCCESSFUL ] com.eed3si9n#sjson-new-core_2.12;0.9.1!sjson-new-core_2.12.jar (927ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/task-system_2.12/1.4.9/task-system_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.12.12!scala-reflect.jar (1172ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/tasks_2.12/1.4.9/tasks_2.12-1.4.9.jar ...
	[SUCCESSFUL ] com.eed3si9n#shaded-scalajson_2.12;1.0.0-M4!shaded-scalajson_2.12.jar (790ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/testing_2.12/1.4.9/testing_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#tasks_2.12;1.4.9!tasks_2.12.jar (227ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-tracking_2.12/1.4.9/util-tracking_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#task-system_2.12;1.4.9!task-system_2.12.jar (514ms)
downloading https://repo1.maven.org/maven2/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0.jar ...
	[SUCCESSFUL ] org.scala-sbt#completion_2.12;1.4.9!completion_2.12.jar (867ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.12/1.4.4/zinc-classpath_2.12-1.4.4.jar ...
	[SUCCESSFUL ] org.jline#jline-terminal;3.19.0!jline-terminal.jar (268ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-apiinfo_2.12/1.4.4/zinc-apiinfo_2.12-1.4.4.jar ...
	[SUCCESSFUL ] org.scala-sbt#util-tracking_2.12;1.4.9!util-tracking_2.12.jar (497ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.12/1.4.4/zinc_2.12-1.4.4.jar ...
	[SUCCESSFUL ] org.scala-sbt#zinc-classpath_2.12;1.4.4!zinc-classpath_2.12.jar (212ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-control_2.12/1.4.9/util-control_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#util-control_2.12;1.4.9!util-control_2.12.jar (200ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/jline/jline/2.14.7-sbt-a1b0ffbb8f64bb820f4f84a0c07a0c0964507493/jline-2.14.7-sbt-a1b0ffbb8f64bb820f4f84a0c07a0c0964507493.jar ...
	[SUCCESSFUL ] org.scala-sbt#testing_2.12;1.4.9!testing_2.12.jar (889ms)
downloading https://repo1.maven.org/maven2/org/jline/jline-reader/3.19.0/jline-reader-3.19.0.jar ...
	[SUCCESSFUL ] org.scala-sbt.jline#jline;2.14.7-sbt-a1b0ffbb8f64bb820f4f84a0c07a0c0964507493!jline.jar (211ms)
downloading https://repo1.maven.org/maven2/org/jline/jline-builtins/3.19.0/jline-builtins-3.19.0.jar ...
	[SUCCESSFUL ] org.scala-sbt#zinc-apiinfo_2.12;1.4.4!zinc-apiinfo_2.12.jar (810ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.4.9/util-interface-1.4.9.jar ...
	[SUCCESSFUL ] org.scala-sbt#zinc_2.12;1.4.4!zinc_2.12.jar (775ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/core-macros_2.12/1.4.9/core-macros_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.jline#jline-builtins;3.19.0!jline-builtins.jar (248ms)
downloading https://repo1.maven.org/maven2/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0.jar ...
	[SUCCESSFUL ] org.jline#jline-terminal-jna;3.19.0!jline-terminal-jna.jar (199ms)
downloading https://repo1.maven.org/maven2/org/jline/jline-terminal-jansi/3.19.0/jline-terminal-jansi-3.19.0.jar ...
	[SUCCESSFUL ] org.jline#jline-reader;3.19.0!jline-reader.jar (813ms)
downloading https://repo1.maven.org/maven2/com/lmax/disruptor/3.4.2/disruptor-3.4.2.jar ...
	[SUCCESSFUL ] org.jline#jline-terminal-jansi;3.19.0!jline-terminal-jansi.jar (196ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.12/scala-compiler-2.12.12.jar ...
	[SUCCESSFUL ] org.scala-sbt#util-interface;1.4.9!util-interface.jar (764ms)
downloading https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.1.0/jansi-2.1.0.jar ...
	[SUCCESSFUL ] org.scala-sbt#core-macros_2.12;1.4.9!core-macros_2.12.jar (782ms)
downloading https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.5.0/jna-5.5.0.jar ...
	[SUCCESSFUL ] com.lmax#disruptor;3.4.2!disruptor.jar (816ms)
downloading https://repo1.maven.org/maven2/net/java/dev/jna/jna-platform/5.5.0/jna-platform-5.5.0.jar ...
	[SUCCESSFUL ] org.fusesource.jansi#jansi;2.1.0!jansi.jar (868ms)
downloading https://repo1.maven.org/maven2/org/jline/jline-style/3.19.0/jline-style-3.19.0.jar ...
	[SUCCESSFUL ] net.java.dev.jna#jna;5.5.0!jna.jar (1401ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-cache_2.12/1.4.9/util-cache_2.12-1.4.9.jar ...
	[SUCCESSFUL ] org.jline#jline-style;3.19.0!jline-style.jar (760ms)
downloading https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-murmurhash_2.12/0.9.1/sjson-new-murmurhash_2.12-0.9.1.jar ...
	[SUCCESSFUL ] org.scala-sbt#util-cache_2.12;1.4.9!util-cache_2.12.jar (828ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/test-agent/1.4.9/test-agent-1.4.9.jar ...
	[SUCCESSFUL ] com.eed3si9n#sjson-new-murmurhash_2.12;0.9.1!sjson-new-murmurhash_2.12.jar (774ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar ...
	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.12.12!scala-compiler.jar (3153ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.4.4/compiler-bridge_2.12-1.4.4.jar ...
	[SUCCESSFUL ] org.scala-sbt#test-agent;1.4.9!test-agent.jar (744ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.12/1.4.4/zinc-classfile_2.12-1.4.4.jar ...
	[SUCCESSFUL ] org.scala-sbt#test-interface;1.0!test-interface.jar (755ms)
downloading https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.54/jsch-0.1.54.jar ...
	[SUCCESSFUL ] net.java.dev.jna#jna-platform;5.5.0!jna-platform.jar (2725ms)
downloading https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-okhttp_2.12/0.5.0/gigahorse-okhttp_2.12-0.5.0.jar ...
	[SUCCESSFUL ] org.scala-sbt#zinc-classfile_2.12;1.4.4!zinc-classfile_2.12.jar (235ms)
downloading https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp-urlconnection/3.7.0/okhttp-urlconnection-3.7.0.jar ...
	[SUCCESSFUL ] org.scala-sbt#compiler-bridge_2.12;1.4.4!compiler-bridge_2.12.jar (537ms)
downloading https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-core_2.12/0.5.0/gigahorse-core_2.12-0.5.0.jar ...
	[SUCCESSFUL ] com.squareup.okhttp3#okhttp-urlconnection;3.7.0!okhttp-urlconnection.jar (211ms)
downloading https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/3.14.2/okhttp-3.14.2.jar ...
	[SUCCESSFUL ] com.squareup.okhttp3#okhttp;3.14.2!okhttp.jar (293ms)
downloading https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.4.0/ssl-config-core_2.12-0.4.0.jar ...
	[SUCCESSFUL ] com.jcraft#jsch;0.1.54!jsch.jar (812ms)
downloading https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar ...
	[SUCCESSFUL ] com.eed3si9n#gigahorse-okhttp_2.12;0.5.0!gigahorse-okhttp_2.12.jar (810ms)
downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.jar ...
	[SUCCESSFUL ] com.typesafe#ssl-config-core_2.12;0.4.0!ssl-config-core_2.12.jar(bundle) (275ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.jar ...
	[SUCCESSFUL ] com.eed3si9n#gigahorse-core_2.12;0.5.0!gigahorse-core_2.12.jar (814ms)
downloading https://repo1.maven.org/maven2/com/typesafe/config/1.3.3/config-1.3.3.jar ...
	[SUCCESSFUL ] org.scala-lang.modules#scala-parser-combinators_2.12;1.1.2!scala-parser-combinators_2.12.jar(bundle) (257ms)
downloading https://repo1.maven.org/maven2/com/squareup/okio/okio/1.17.2/okio-1.17.2.jar ...
	[SUCCESSFUL ] com.squareup.okio#okio;1.17.2!okio.jar (205ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.12/1.4.4/zinc-core_2.12-1.4.4.jar ...
	[SUCCESSFUL ] org.reactivestreams#reactive-streams;1.0.2!reactive-streams.jar (774ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.12/1.4.4/zinc-persist_2.12-1.4.4.jar ...
	[SUCCESSFUL ] org.slf4j#slf4j-api;1.7.26!slf4j-api.jar (781ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.12/1.4.4/zinc-compile-core_2.12-1.4.4.jar ...
	[SUCCESSFUL ] org.scala-sbt#zinc-core_2.12;1.4.4!zinc-core_2.12.jar (313ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist-core-assembly/1.4.4/zinc-persist-core-assembly-1.4.4.jar ...
	[SUCCESSFUL ] com.typesafe#config;1.3.3!config.jar(bundle) (855ms)
downloading https://repo1.maven.org/maven2/net/openhft/zero-allocation-hashing/0.10.1/zero-allocation-hashing-0.10.1.jar ...
	[SUCCESSFUL ] org.scala-sbt#zinc-persist-core-assembly;1.4.4!zinc-persist-core-assembly.jar (890ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/sbinary_2.12/0.5.1/sbinary_2.12-0.5.1.jar ...
	[SUCCESSFUL ] org.scala-sbt#zinc-compile-core_2.12;1.4.4!zinc-compile-core_2.12.jar (932ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/protocol_2.12/1.4.9/protocol_2.12-1.4.9.jar ...
	[SUCCESSFUL ] net.openhft#zero-allocation-hashing;0.10.1!zero-allocation-hashing.jar(bundle) (773ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.jar ...
	[SUCCESSFUL ] org.scala-sbt#zinc-persist_2.12;1.4.4!zinc-persist_2.12.jar (1123ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/ipcsocket/ipcsocket/1.3.0/ipcsocket-1.3.0.jar ...
	[SUCCESSFUL ] org.scala-sbt#sbinary_2.12;0.5.1!sbinary_2.12.jar (245ms)
downloading https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.4.1/checker-qual-3.4.1.jar ...
	[SUCCESSFUL ] org.checkerframework#checker-qual;3.4.1!checker-qual.jar (244ms)
downloading https://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.4.0/error_prone_annotations-2.4.0.jar ...
	[SUCCESSFUL ] com.google.errorprone#error_prone_annotations;2.4.0!error_prone_annotations.jar (211ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.3.2/scala-collection-compat_2.12-2.3.2.jar ...
	[SUCCESSFUL ] org.scala-sbt#template-resolver;0.1!template-resolver.jar (752ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-fbc4f586aeeb1591710b14eb4f41b94880dcd745/ivy-2.3.0-sbt-fbc4f586aeeb1591710b14eb4f41b94880dcd745.jar ...
	[SUCCESSFUL ] org.scala-lang.modules#scala-collection-compat_2.12;2.3.2!scala-collection-compat_2.12.jar (252ms)
	[SUCCESSFUL ] org.scala-sbt.ipcsocket#ipcsocket;1.3.0!ipcsocket.jar (782ms)
	[SUCCESSFUL ] org.scala-sbt#protocol_2.12;1.4.9!protocol_2.12.jar (1360ms)
	[SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-fbc4f586aeeb1591710b14eb4f41b94880dcd745!ivy.jar (1147ms)
:: retrieving :: org.scala-sbt#boot-app
	confs: [default]
	83 artifacts copied, 0 already retrieved
[info] [launcher] getting Scala 2.12.12 (for sbt)...
downloading https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar ...
downloading https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.12/jansi-1.12.jar ...
downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar ...
	[SUCCESSFUL ] jline#jline;2.14.6!jline.jar (907ms)
	[SUCCESSFUL ] org.fusesource.jansi#jansi;1.12!jansi.jar (1512ms)
	[SUCCESSFUL ] org.scala-lang.modules#scala-xml_2.12;1.0.6!scala-xml_2.12.jar(bundle) (1796ms)
:: retrieving :: org.scala-sbt#boot-scala
	confs: [default]
	6 artifacts copied, 0 already retrieved

	at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:57)
	at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:53)
	at cats.effect.IOFiber.flatMapK(IOFiber.scala:1204)
	at cats.effect.IOFiber.succeeded(IOFiber.scala:1004)
	at cats.effect.IOFiber.afterBlockingSuccessfulR(IOFiber.scala:1153)
	at cats.effect.IOFiber.run(IOFiber.scala:129)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:358)
2021-05-10 12:19:55,158 INFO  ──────────── Total time: Steward xxxxxxx: 1m 57s 363ms ────────────
2021-05-10 12:19:55,168 INFO  ──────────── Total time: run: 2m 11s 336ms ────────────
```

Running it with `sbt stage` works fine. I am digging a bit to see If I can get more info, I'll post it, but so far nothing.
