### ISSUE TITLE
Scala steward is failing

### ISSUE THREAD

**Issue by bilal-fazlani** [scala-steward-org/scala-steward#1819]
Hi, 
Moving the [original issue](https://github.com/scala-steward-org/scala-steward-action/issues/200)  here since this is appropriate repo.

I need help understanding what I can do to make it work.
Scala-Steward github action is failing for some syntax errors.

https://github.com/bilal-fazlani/scalabar/runs/1583191773?check_suite_focus=true

```bash
  2020-12-20 01:04:11,790 ERROR Steward ***/scalabar failed
  java.io.IOException: '"SBT_OPTS=-Xmx2048m -Xss8m -XX:MaxMetaspaceSize=512m" scalafmt --non-interactive' exited with code 2
  Align: top-level presets deprecated; use 'preset' subsection
  Reformatting...
  Reformatting... (5.88 %, 1 / 17)
  
  /home/runner/scala-steward/workspace/repos/***/scalabar/scalabar/src/main/scala/com/bilalfazlani/scalabar/ScalaBarApp.scala:10: error: expected class or object definition
  type Handler = PartialFunction[(String, Option[String]), Unit]
  ^
  /home/runner/scala-steward/workspace/repos/***/scalabar/scalabar/src/main/scala/com/bilalfazlani/scalabar/dsl/MenuDsl.scala:10: error: expected class or object definition
  type AllowedType = Text | Link | DispatchAction | ShellCommand | MenuBuilder
  ^
  /home/runner/scala-steward/workspace/repos/***/scalabar/scalabar/src/main/scala/com/bilalfazlani/scalabar/dsl/HandlerDsl.scala:11: error: expected class or object definition
  type MetadataFunction = Option[String] => Unit
  ^
  
  	at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:54)
  	at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:50)
  	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:242)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:241)
  	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:218)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:240)
  	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:218)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$close$2(CompileScope.scala:238)
  	at flatMap @ fs2.internal.CompileScope.close(CompileScope.scala:237)
  	at main$ @ org.scalasteward.core.Main$.main(Main.scala:22)
  	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:429)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$openAncestor$2(CompileScope.scala:257)
  	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$15(Algebra.scala:532)
  	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:242)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:241)
  	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:218)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:240)
  2020-12-20 01:04:11,799 INFO  ──────────── Total time: Steward ***/scalabar: 1m 35s 952ms ────────────
  2020-12-20 01:04:11,802 INFO  ──────────── Total time: run: 1m 37s 630ms ────────────
Error:  ✕ Launching org.scala-steward:scala-steward-core_2.13:0.8.1 failed
```

**Comment by fthomas** [comment]
Scala Steward ran `scalafmt` which exited with an error because it couldn't format your source files. This problem was fixed by #1796 which will be included in the next version. A temporary fix until 0.9 is released, is to set the Scala Steward version in the GH Action to the latest SNAPSHOT version.

**Comment by bilal-fazlani** [comment]
Thank you! Where can I find the latest snapshot version number ?

**Comment by fthomas** [comment]
[Here](https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-core_2.13/) for example. The latest is currently 0.8.1-127-22ecafb3-SNAPSHOT.

**Comment by bilal-fazlani** [comment]
Thank you very much 😁
