### ISSUE TITLE
scala-steward fails to load subproject from GitHub uri

### ISSUE THREAD

**Issue by j-chimienti** [scala-steward-org/scala-steward#1880]
stewardDependencies fails for a sub-project loaded via GitHub uri

```
val gtag = "a23cb864b873bb2d859dde6b0f3d476f5862490e"
lazy val paymodel = RootProject(
  uri(s"https://github.com/JWWeatherman/pay-model.git#$gtag")
)

lazy val root = (project in file("."))
  .aggregate(core, server, paymodel)


```

```
[error] Expected project ID
[error] Expected configuration
[error] Expected ':'
[error] Expected key
[error] Not a valid key: paymodel (similar: name)
[error] all pollofeed/stewardDependencies core/stewardDependencies server/stewardDependencies paymodel/stewardDependencies
[error]                                                                                               ^

        at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:58)
        at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:54)
        at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
        at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:245)
        at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
        at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:244)
        at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
        at flatMap @ fs2.internal.CompileScope.$anonfun$close$2(CompileScope.scala:242)
        at flatMap @ fs2.internal.CompileScope.close(CompileScope.scala:241)
        at main$ @ org.scalasteward.core.Main$.main(Main.scala:22)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
        at flatMap @ fs2.internal.CompileScope.$anonfun$openAncestor$2(CompileScope.scala:261)
        at flatMap @ fs2.internal.FreeC$.$anonfun$compile$17(Algebra.scala:545)
        at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
        at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:245)
        at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
        at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:244)

```

**Comment by j-chimienti** [comment]
Versioning issue on my end.
