### ISSUE TITLE
Cannot run program "scalafmt" once for the workspace, once in case of a monorepo

### ISSUE THREAD

**Issue by robstoll** [scala-steward-org/scala-steward#1890]
I get the following error when running scala-steward (using 26591b84)
```
java.io.IOException: Cannot run program "scalafmt" (in directory "/builds/tegonal/scala-steward/data/workspace"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.scalasteward.core.io.process$.$anonfun$createProcess$1(process.scala:82)
	at flatMap @ org.scalasteward.core.io.process$.slurp(process.scala:44)
	at ifM$extension @ io.chrisdavenport.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.info(Slf4jLoggerInternal.scala:76)
	at >>$extension @ org.scalasteward.core.scalafix.MigrationsLoader.loadMigrations(MigrationsLoader.scala:43)
	at flatMap @ org.scalasteward.core.scalafmt.ScalafmtAlg$$anon$1.version(ScalafmtAlg.scala:55)
	at map @ org.scalasteward.core.scalafmt.ScalafmtAlg$$anon$1.version(ScalafmtAlg.scala:56)
	at flatMap @ org.scalasteward.core.application.SelfCheckAlg.checkScalafmtBinary(SelfCheckAlg.scala:49)
	at flatMap @ org.scalasteward.core.application.SelfCheckAlg.$anonfun$checkAll$3(SelfCheckAlg.scala:38)
	at ifM$extension @ io.chrisdavenport.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.info(Slf4jLoggerInternal.scala:76)
	at timeoutTo @ org.scalasteward.core.io.process$.$anonfun$slurp$3(process.scala:67)
	at flatMap @ org.scalasteward.core.io.process$.$anonfun$slurp$1(process.scala:45)
	at flatMap @ org.scalasteward.core.io.process$.slurp(process.scala:44)
	at ifM$extension @ io.chrisdavenport.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.info(Slf4jLoggerInternal.scala:76)
	at >>$extension @ org.scalasteward.core.scalafix.MigrationsLoader.loadMigrations(MigrationsLoader.scala:43)
	at flatMap @ org.scalasteward.core.git.FileGitAlg.version(FileGitAlg.scala:152)
	at map @ org.scalasteward.core.git.FileGitAlg.version(FileGitAlg.scala:152)
	at flatMap @ org.scalasteward.core.application.SelfCheckAlg.checkGitBinary(SelfCheckAlg.scala:43)
```

Since scala-steward continues it's not really a problem more a minor flaw. I guess it would suffice to log "could not load scalafmt migrations"

And I get a similar error for every monorepo which does not have a scala project in the root. For instance, one project has the following config:
```
buildRoots = [ "server" ]
```
The error is the following:
```
java.io.IOException: Cannot run program "scalafmt" (in directory "/builds/tegonal/scala-steward/data/workspace/repos/myproject"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.scalasteward.core.io.process$.$anonfun$createProcess$1(process.scala:82)
	at flatMap @ org.scalasteward.core.io.process$.slurp(process.scala:44)
	at ifM$extension @ io.chrisdavenport.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.info(Slf4jLoggerInternal.scala:76)
	at >>$extension @ org.scalasteward.core.scalafix.MigrationsLoader.loadMigrations(MigrationsLoader.scala:43)
	at flatMap @ org.scalasteward.core.util.logger$LoggerOps$.attemptLogImpl_$extension(logger.scala:48)
	at flatMap @ org.scalasteward.core.edit.hooks.HookExecutor.$anonfun$execPostUpdateHook$3(HookExecutor.scala:55)
	at flatMap @ org.scalasteward.core.edit.hooks.HookExecutor.$anonfun$execPostUpdateHook$2(HookExecutor.scala:54)
	at ifM$extension @ io.chrisdavenport.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.info(Slf4jLoggerInternal.scala:76)
	at flatMap @ org.scalasteward.core.edit.hooks.HookExecutor.execPostUpdateHook(HookExecutor.scala:53)
	at flatTraverse @ org.scalasteward.core.scalafix.MigrationsLoader.loadAll(MigrationsLoader.scala:38)
	at flatTraverse @ org.scalasteward.core.scalafix.MigrationsLoader.loadAll(MigrationsLoader.scala:38)
	at flatTraverse @ org.scalasteward.core.scalafix.MigrationsLoader.loadAll(MigrationsLoader.scala:38)
	at flatTraverse @ org.scalasteward.core.scalafix.MigrationsLoader.loadAll(MigrationsLoader.scala:38)
	at map @ org.scalasteward.core.edit.EditAlg.$anonfun$applyUpdate$7(EditAlg.scala:70)
	at timeoutTo @ org.scalasteward.core.io.process$.$anonfun$slurp$3(process.scala:67)
	at flatMap @ org.scalasteward.core.io.process$.$anonfun$slurp$1(process.scala:45)
	at flatMap @ org.scalasteward.core.io.process$.slurp(process.scala:44)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.scalasteward.core.io.process$.$anonfun$createProcess$1(process.scala:82)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:104)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)
	at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:474)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:482)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:422)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:183)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:484)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:422)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by GrafBlutwurst** [comment]
How do you run scala-steward? while I was testing i observed the same issue and resolved it by having `scalafmt` on my path

**Comment by mzuehlke** [comment]
In it's self check `scala-steward` check wheather

**Comment by robstoll** [comment]
I am running it as follows (in gitlab):
```
  script:
    - sbt stage
    - |
      ./modules/core/.jvm/target/universal/stage/bin/scala-steward \
          --workspace  "data/workspace" \
          --repos-file "data/repos.md" \
          --git-author-name "Scala Steward" \
          --git-author-email "scala.steward@tegonal.com" \
          --vcs-type "gitlab" \
          --vcs-api-host "https://xyz/api/v4" \
          --vcs-login "dddd" \
          --git-ask-pass "data/login.sh" \
          --disable-sandbox
```

**Comment by fthomas** [comment]
For reformatting the source code on scalafmt updates, Scala Steward needs the `scalafmt` binary on the `PATH`. Similar to how it needs `git` and `sbt` binaries on the PATH. One way to get the binary is via [Coursier](https://get-coursier.io/docs/cli-installation) (`coursier install scalafmt`).

**Comment by robstoll** [comment]
The warning @mzuehlke mentioned is actually there. My bad that I have not realised that it is actually the log message to the exception. I created a PR to improve the error message so that others don't have to come here and ask (hopefully).
