### ISSUE TITLE
Docker run causing java.net.UnknownHostException: raw.githubusercontent.com

### ISSUE THREAD

**Issue by robbyki** [scala-steward-org/scala-steward#2082]
This has been working for a while for private repos. not sure what's happening here or how to debug this. 

```
Exception in thread "main" java.net.UnknownHostException: raw.githubusercontent.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at java.net.URL.openStream(URL.java:1045)
        at scala.io.Source$.fromURL(Source.scala:144)
        at scala.io.Source$.fromURL(Source.scala:134)
        at org.scalasteward.core.io.FileAlg$$anon$1.$anonfun$readUri$2(FileAlg.scala:134)
        at cats.effect.IOFiber.blockingR(IOFiber.scala:1136)
        at cats.effect.IOFiber.run(IOFiber.scala:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

and my docker run:
```
docker run -v $STEWARD_DIR:/opt/scala-steward -it fthomas/scala-steward:latest \
  --workspace  "/opt/scala-steward/workspace" \
  --repos-file "/opt/scala-steward/repos.md" \
  --do-not-fork \
  --default-repo-conf "/opt/scala-steward/default.scala-steward.conf" \
  --git-author-email "<mygituseremail>" \
  --vcs-api-host "https://github.ibm.com/api/v3" \
  --vcs-login "<mygituser>" \
  --git-ask-pass "/opt/scala-steward/pass.sh" \
  --sign-commits
```

**Comment by fthomas** [comment]
@robbyki I assume you closed it because it was some transient network fault?

**Comment by robbyki** [comment]
Sorry @fthomas should not have closed it so soon. I switched to using `sbt stage ./modules/core...` instead of Docker. Still have no idea why I still get that strange network issue with `raw.githubusercontent.com`. I have verified with multiple connections and still get that error.
