### ISSUE TITLE
Scala-steward can't force-push to its own gitlab.com fork

### ISSUE THREAD

**Issue by nafg** [scala-steward-org/scala-steward#2103]
As discussed on gitter, my repo, https://gitlab.com/io.github.nafg/slick-migration-api, stopped receiving update MRs. @fthomas posted the error log:

```
2021-04-07 19:07:35,461 INFO  ──────────── Steward io.github.nafg/slick-migration-api ────────────
2021-04-07 19:07:35,462 INFO  Check cache of io.github.nafg/slick-migration-api
2021-04-07 19:07:37,806 INFO  Clone scala-steward/slick-migration-api
2021-04-07 19:07:38,582 INFO  Synchronize with io.github.nafg/slick-migration-api
2021-04-07 19:07:43,576 ERROR Steward io.github.nafg/slick-migration-api failed
java.io.IOException: 'git push --force --set-upstream origin master' exited with code 1
remote: GitLab: You are not allowed to force push code to a protected branch on this project.
To https://gitlab.com/scala-steward/slick-migration-api.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://scala-steward@gitlab.com/scala-steward/slick-migration-api.git'

    at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:58)
    at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:54)
    at cats.effect.IOFiber.flatMapK(IOFiber.scala:1164)
    at cats.effect.IOFiber.succeeded(IOFiber.scala:958)
    at cats.effect.IOFiber.afterBlockingSuccessfulR(IOFiber.scala:1113)
    at cats.effect.IOFiber.run(IOFiber.scala:141)
    at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:372)
2021-04-07 19:07:43,577 INFO  ──────────── Total time: Steward io.github.nafg/slick-migration-api: 8s 116ms ────────────
```

I think I'm using the default gitlab settings so I'm not sure why it works for other people and not for me.

What I'm guessing is happening is this:
 - Scala-steward forks the gitlab repo
 - Perhaps when gitlab forks a repo that results in a repo that has the same branch protection settings as the repo it's forking from
 - As part of scala-steward's process, it synchronizes its fork's master branch to upstream's HEAD. If a force-push has been done upstream, syncing requires a force-push downstream too.

I changed my repo's settings to allow force-push to protected branches, however I doubt that would help since it's the permissions in the fork that matter. And I doubt my settings will get synced since I doubt this behavior is intentional; I'm guessing scala-steward doesn't update these settings at all.

Perhaps a solution would be that when scala-steward forks a repo (and perhaps as a one-time thing, for already-forked repos) it should explicitly set `allow_force_push` in a POST to the protected branches API (see https://docs.gitlab.com/ee/api/protected_branches.html#protect-repository-branches).

As an attempted workaround I've merged the scala-steward fork into my own with `-s ours`. That way the next time it syncs it should be a fast-forward.

**Comment by daddykotex** [comment]
Hey, how are you?

Do you use the community Scala Steward or you run it yourself? If you do run it yourself, note that you can run Scala Steward without forking. There is a `--do-not-fork` option you can pass. I'm not sure it will solve your issue though.

**Comment by nafg** [comment]
The community one

**Comment by fthomas** [comment]
Closing since the public GitLab instance has been shut down on 2022-06-01 and there is no way for me to reproduce or fix this anymore.
