### ISSUE TITLE
No new pull request since default branch changed from 'master' to 'main'

### ISSUE THREAD

**Issue by lefou** [scala-steward-org/scala-steward#2148]
In https://github.com/com-lihaoyi/mill we no longer see updates since we changed our default branch.

**Comment by lefou** [comment]
@fthomas Any idea what's the reason?

**Comment by fthomas** [comment]
It does not seem to be related to the change of the default branch. The problem is that Scala Steward could not extract the dependencies from the Mill build via the scala-steward-mill-plugin:
```
mill -i -p ~/scala-steward/workspace/repos/com-lihaoyi/mill/scala-steward.sc show org.scalasteward.mill.plugin.StewardPlugin/extractDeps' exited with code 1:
Preparing Java 11.0.10 runtime; this may take a minute or two ...
Compiling ~/scala-steward/workspace/repos/com-lihaoyi/mill/scala-steward.sc
Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT.pom
Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT.pom
Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT.pom.sha1
Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT.pom.sha1
Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/maven-metadata.xml
Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/maven-metadata.xml
Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/maven-metadata.xml.sha1
Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/maven-metadata.xml.sha1
Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT.pom
Downloaded https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT.pom
Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT.pom.sha1
Downloaded https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT.pom.sha1
Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT.jar
Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT-sources.jar
Downloaded https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT-sources.jar
Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT-sources.jar.sha1
Downloaded https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT-sources.jar.sha1
Downloaded https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT.jar
Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT.jar.sha1
Downloaded https://oss.sonatype.org/content/repositories/snapshots/org/scala-steward/scala-steward-mill-plugin_2.13/0.9.1-284-44cabcff-SNAPSHOT/scala-steward-mill-plugin_2.13-0.9.1-284-44cabcff-SNAPSHOT.jar.sha1
Compiling ~/scala-steward/workspace/repos/com-lihaoyi/mill/ci/shared.sc
Compiling ~/scala-steward/workspace/repos/com-lihaoyi/mill/ci/upload.sc
Compiling ~/scala-steward/workspace/repos/com-lihaoyi/mill/build.sc
[1/1] show 
Exception in thread \"main\" java.lang.NoSuchMethodError: 'boolean mainargs.arg$.$lessinit$greater$default$5()'
  at org.scalasteward.mill.plugin.StewardPlugin$.$anonfun$millDiscover$1(StewardPlugin.scala:70)
  at org.scalasteward.mill.plugin.StewardPlugin$.millDiscover$lzycompute(StewardPlugin.scala:70)
  at org.scalasteward.mill.plugin.StewardPlugin$.millDiscover(StewardPlugin.scala:70)
  at mill.main.RunScript$.$anonfun$resolveTasks$4(RunScript.scala:145)
  at scala.util.Either.map(Either.scala:382)
  at mill.main.RunScript$.$anonfun$resolveTasks$3(RunScript.scala:134)
  at scala.collection.immutable.List.map(List.scala:246)
  at mill.main.RunScript$.$anonfun$resolveTasks$2(RunScript.scala:133)
  at scala.util.Either.flatMap(Either.scala:352)
  at mill.main.RunScript$.resolveTasks(RunScript.scala:130)
  at mill.main.RunScript$.evaluateTasks(RunScript.scala:187)
  at mill.main.MainModule$.evaluateTasks(MainModule.scala:20)
  at mill.main.MainModule.$anonfun$show$1(MainModule.scala:203)
  at mill.define.Applicative$Applyer.$anonfun$zipMap$1(Applicative.scala:35)
  at mill.define.Task$MappedDest.evaluate(Task.scala:391)
  at mill.eval.Evaluator.$anonfun$evaluateGroup$13(Evaluator.scala:491)
  at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
  at scala.Console$.withErr(Console.scala:193)
  at mill.eval.Evaluator.$anonfun$evaluateGroup$12(Evaluator.scala:491)
  at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
  at scala.Console$.withOut(Console.scala:164)
  at mill.eval.Evaluator.$anonfun$evaluateGroup$11(Evaluator.scala:490)
  at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
  at scala.Console$.withIn(Console.scala:227)
  at mill.eval.Evaluator.$anonfun$evaluateGroup$8(Evaluator.scala:489)
  at mill.eval.Evaluator.$anonfun$evaluateGroup$8$adapted(Evaluator.scala:441)
  at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
  at mill.eval.Evaluator.evaluateGroup(Evaluator.scala:441)
  at mill.eval.Evaluator.$anonfun$evaluateGroupCached$13(Evaluator.scala:343)
  at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
  at mill.eval.Evaluator.evaluateGroupCached(Evaluator.scala:334)
  at mill.eval.Evaluator.$anonfun$sequentialEvaluate$2(Evaluator.scala:117)
  at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
  at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
  at mill.eval.Evaluator.sequentialEvaluate(Evaluator.scala:94)
  at mill.eval.Evaluator.evaluate(Evaluator.scala:80)
  at mill.main.RunScript$.evaluate(RunScript.scala:202)
  at mill.main.RunScript$.$anonfun$evaluateTasks$1(RunScript.scala:188)
  at scala.util.Either.map(Either.scala:382)
  at mill.main.RunScript$.evaluateTasks(RunScript.scala:187)
  at mill.main.RunScript$.$anonfun$runScript$4(RunScript.scala:66)
  at ammonite.util.Res$Success.flatMap(Res.scala:62)
  at mill.main.RunScript$.runScript(RunScript.scala:65)
  at mill.main.MainRunner.$anonfun$runScript$1(MainRunner.scala:118)
  at mill.main.MainRunner.watchLoop2(MainRunner.scala:67)
  at mill.main.MainRunner.runScript(MainRunner.scala:93)
  at mill.MillMain$.main0(MillMain.scala:215)
  at mill.MillMain$.main(MillMain.scala:83)
  at mill.MillMain.main(MillMain.scala)
```
I've no idea what's wrong here.

**Comment by lefou** [comment]
Thanks for that info! It seems to work now again. I suspect some binary incompatibilities which probably got resolved, but that's only a wild guess. I've seen some binary issues in com-lihaoyi libs in micro releases in the past. I'm closing this one for now.
