### ISSUE TITLE
 java.lang.NoClassDefFoundError: scala/Serializable

### ISSUE THREAD

**Issue by florianmutter** [scala-steward-org/scala-steward#2170]
One of our repositories produces an error in scala steward. It seems to want to to something with scala 2.13. In the built.sbt are multiple projects that all have `scalaVersion` set to `2.12.12`. It is a private repository. Do you have any idea what the issue could be?

```
  2021-06-29 20:11:59,353 INFO  ──────────── Steward fid-dev/CMOS ────────────
  2021-06-29 20:11:59,354 INFO  Check cache of fid-dev/CMOS
  2021-06-29 20:11:59,799 INFO  Clone fid-dev/CMOS
  2021-06-29 20:12:00,727 INFO  Refresh cache of fid-dev/CMOS
  2021-06-29 20:12:00,733 INFO  Parsed RepoConfig(CommitsConfig(None),PullRequestsConfig(Some(Timespan(30 days))),ScalafmtConfig(None),UpdatesConfig(List(),List(),List(),None,None,None),None,None)
  2021-06-29 20:12:05,528 ERROR Steward fid-dev/CMOS failed
  java.io.IOException: '"SBT_OPTS=-Xmx2048m -Xss8m -XX:MaxMetaspaceSize=512m" sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 1
  [info] [launcher] getting org.scala-sbt sbt 1.4.1  (this may take some time)...
  [info] [launcher] getting Scala 2.13.3 (for sbt)...
  java.lang.NoClassDefFoundError: scala/Serializable
  	at sbt.internal.ClassLoaderWarmup$.warmup(XMainConfiguration.scala:31)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:82)
  	at sbt.xMain.run(Main.scala:46)
  	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
  	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
  	at xsbt.boot.Launch$.run(Launch.scala:149)
  	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
  	at xsbt.boot.Launch$.launch(Launch.scala:159)
  	at xsbt.boot.Launch$.apply(Launch.scala:44)
  	at xsbt.boot.Launch$.apply(Launch.scala:21)
  	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
  	at xsbt.boot.Boot$.run(Boot.scala:73)
  	at xsbt.boot.Boot$.main(Boot.scala:21)
  	at xsbt.boot.Boot.main(Boot.scala)
  Caused by: java.lang.ClassNotFoundException: scala.Serializable
  	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  	... 18 more
  Error:  [launcher] error during sbt launcher: java.lang.NoClassDefFoundError: scala/Serializable
  
  	at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:58)
  	at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:54)
  	at delay$extension @ fs2.io.package$.readBytesFromInputStream(io.scala:95)
  	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:245)
  	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:244)
  	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$close$2(CompileScope.scala:242)
  	at flatMap @ fs2.internal.CompileScope.close(CompileScope.scala:241)
  	at main$ @ org.scalasteward.core.Main$.main(Main.scala:22)
  	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$openAncestor$2(CompileScope.scala:261)
  	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$17(Algebra.scala:545)
  	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
  2021-06-29 20:12:05,531 INFO  ──────────── Total time: Steward fid-dev/CMOS: 6s 178ms ────────────
  ```

**Comment by fthomas** [comment]
This looks similar to this issue: https://github.com/scala-steward-org/scala-steward-action/issues/244

**Comment by florianmutter** [comment]
You are right. Looks like it is the same. So is the problem that scala steward is running with scala 2.13 but one or more dependencies in our project is not available for 2.13?

**Comment by fthomas** [comment]
The Scala version Scala Steward uses should be irrelevant. It executes an sbt task in your project to get the dependencies and will use the sbt and Scala version that is defined in your project. Can you run sbt in this project without using Scala Steward?

**Comment by florianmutter** [comment]
Yes sbt locally works. I removed some waring about our code but this is the output:
```
$ sbt
[info] welcome to sbt 1.4.1 (AdoptOpenJDK Java 10.0.2)
[info] loading settings for project global-plugins from idea.sbt,plugins.sbt,sbt-updates.sbt ...
[info] loading global plugins from /Users/florianmutter/.sbt/1.0/plugins
[info] loading settings for project cmos-build from plugins.sbt ...
[info] loading project definition from /Users/florianmutter/Developer/CMOS/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[success] Generated .bloop/cmos-build.json
[success] Total time: 6 s, completed 30.06.2021, 10:21:17
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] loading settings for project cmos from build.sbt ...
[info] set current project to cmos (in build file:/Users/florianmutter/Developer/CMOS/)
[warn] there are 2 keys that are not used by any other settings/tasks:
[warn]  
[warn] * kkmImport / mainClass
[warn]   +- /Users/florianmutter/Developer/CMOS/build.sbt:139
[warn] * kubiImport / mainClass
[warn]   +- /Users/florianmutter/Developer/CMOS/build.sbt:117
[warn]  
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
[info] sbt server started at local:///Users/florianmutter/.sbt/1.0/server/38492c153b1f02f873ad/sock
sbt:cmos> clean
[success] Total time: 1 s, completed 30.06.2021, 10:21:36
sbt:cmos> compile
[info] compiling 3 Scala sources to /Users/florianmutter/Developer/CMOS/tools/dbMigration/target/scala-2.12/classes ...
https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.4.1/compiler-bridge_2.12-1.4.1-sources.jar
  100,0% [##########] 52,4 KiB (111,7 KiB / s)
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.12. Compiling...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Updating 
https://fidrepository.jfrog.io/fidrepository/libs-snapshot-local/de/fashionid/crm-kubi-data-import-base_2.12/0.0.10-SNAPSHOT/crm-kubi-data-import-base_2.12-0.0.10-SNAPSHOT.pom
  No new update since 2017-12-15 10:03:28
https://fidrepository.jfrog.io/fidrepository/libs-snapshot-local/de/fashionid/crm-scala-service-base-slick-support_2.12/0.2.4-SNAPSHOT/crm-scala-service-base-slick-support_2.12-0.2.4-SNAPSHOT.pom
  No new update since 2017-12-08 19:41:44
https://fidrepository.jfrog.io/fidrepository/libs-snapshot-local/de/fashionid/crm-scala-service-base-core_2.12/0.2.4-SNAPSHOT/crm-scala-service-base-core_2.12-0.2.4-SNAPSHOT.pom
  No new update since 2017-12-08 19:41:30
[info] Resolved  dependencies
[info] Fetching artifacts of 
https://fidrepository.jfrog.io/fidrepository/libs-snapshot-local/de/fashionid/crm-scala-service-base-slick-support_2.12/0.2.4-SNAPSHOT/crm-scala-service-base-slick-support_2.12-0.2.4-SNAPSHOT.jar
  No new update since 2017-12-08 19:41:45
https://fidrepository.jfrog.io/fidrepository/libs-snapshot-local/de/fashionid/crm-kubi-data-import-base_2.12/0.0.10-SNAPSHOT/crm-kubi-data-import-base_2.12-0.0.10-SNAPSHOT.jar
  Warning: local copy newer than remote one (2017-12-15 10:03:31 > 2017-12-15 10:03:29)
https://fidrepository.jfrog.io/fidrepository/libs-snapshot-local/de/fashionid/crm-scala-service-base-core_2.12/0.2.4-SNAPSHOT/crm-scala-service-base-core_2.12-0.2.4-SNAPSHOT.jar
  No new update since 2017-12-08 19:41:32
[info] Fetched artifacts of 
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info]   Compilation completed in 14.778s.
[info] compiling 37 Scala sources to /Users/florianmutter/Developer/CMOS/common/target/scala-2.12/classes ...
[warn] ...
[warn] there were 17 deprecation warnings
[warn] there were four deprecation warnings (since 2.11.0)
[warn] there were two deprecation warnings (since 2017-06-21)
[warn] there were four deprecation warnings (since 2018-07-02)
[warn] there was one deprecation warning (since 3.0)
[warn] there were 28 deprecation warnings in total; re-run with -deprecation for details
[warn] 8 warnings found
[info] compiling 3 Scala sources to /Users/florianmutter/Developer/CMOS/tools/legacyStylebopImport/target/scala-2.12/classes ...
[info] compiling 3 Scala sources to /Users/florianmutter/Developer/CMOS/tools/kubiImport/target/scala-2.12/classes ...
[info] compiling 1 Scala source to /Users/florianmutter/Developer/CMOS/tools/anonReExport/target/scala-2.12/classes ...
[info] compiling 15 Scala sources to /Users/florianmutter/Developer/CMOS/tools/kkmImport/target/scala-2.12/classes ...
[warn] /Users/florianmutter/Developer/CMOS/tools/legacyStyle ...
[warn] there was one unchecked warning; re-run with -unchecked for details
[warn] three warnings found
[success] Total time: 64 s (01:04), completed 30.06.2021, 10:22:44
```

**Comment by fthomas** [comment]
Is that the same machine where you're running Scala Steward?

**Comment by florianmutter** [comment]
No we run scala steward as a github action. I'll see if I can run it in a similar env

**Comment by eed3si9n** [comment]
I wonder if I messed something up? https://github.com/sbt/sbt/issues/6587

**Comment by florianmutter** [comment]
I'll try it with setting a newer sbt version for the project

**Comment by florianmutter** [comment]
Updating the sbt version worked. Thanks @eed3si9n !
