### ISSUE TITLE
Update PRs stopped for sttp-shared

### ISSUE THREAD

**Issue by adamw** [scala-steward-org/scala-steward#2196]
For some reason, dependency update PRs stopped for sttp-shared in May: https://github.com/softwaremill/sttp-shared/pulls?q=is%3Apr+is%3Aclosed

For sttp-model, sttp, tapir, it works flawlessly. I can't find what's different about this repository, maybe you could help :)

**Comment by fthomas** [comment]
Scala Steward couldn't load the build:
```
[info] welcome to sbt 1.5.2 (Ubuntu Java 11.0.10)
[info] loading global plugins from $HOME/.sbt/1.0/plugins
[info] compiling 1 Scala source to $HOME/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes ...
[info] done compiling
[info] loading settings for project sttp-shared-build from plugins.sbt ...
[info] loading project definition from $WORKSPACE/repos/softwaremill/sttp-shared/project
[info] STTP_NATIVE *not* defined, *not* including sttp-native in the aggregate projects
java.lang.RuntimeException: project matching List(PlatformAxis(jvm,JVM,jvm)) and 2.11.12 was not found
    at scala.sys.package$.error(package.scala:30)
    at sbt.internal.ProjectMatrix$ProjectMatrixDef$AxisBaseProjectFinder.$anonfun$apply$1(ProjectMatrix.scala:439)
    at scala.Option.getOrElse(Option.scala:189)
    at sbt.internal.ProjectMatrix$ProjectMatrixDef$AxisBaseProjectFinder.apply(ProjectMatrix.scala:439)
    at $7493a44d58d5c719f4de$.$anonfun$projectAggregates$2(build.sbt:77)
    at scala.collection.immutable.List.flatMap(List.scala:366)
    at $7493a44d58d5c719f4de$.projectAggregates$lzycompute(build.sbt:77)
    at $7493a44d58d5c719f4de$.projectAggregates(build.sbt:71)
    at $7493a44d58d5c719f4de$.rootProject$lzycompute(build.sbt:97)
    at $7493a44d58d5c719f4de$.rootProject(build.sbt:94)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at sbt.compiler.EvalDefinitions.$anonfun$values$1(Eval.scala:59)
    at scala.collection.immutable.List.map(List.scala:293)
    at sbt.compiler.EvalDefinitions.values(Eval.scala:59)
    at sbt.internal.DefinedSbtValues.$anonfun$values$1(LoadedSbtFile.scala:50)
    at scala.collection.immutable.List.flatMap(List.scala:366)
    at sbt.internal.DefinedSbtValues.values(LoadedSbtFile.scala:50)
    at sbt.internal.EvaluateConfigurations$.$anonfun$evaluateSbtFile$4(EvaluateConfigurations.scala:166)
    at sbt.internal.Load$.loadSettingsFile$1(Load.scala:1108)
    at sbt.internal.Load$.$anonfun$discoverProjects$2(Load.scala:1117)
    at scala.collection.MapLike.getOrElse(MapLike.scala:131)
    at scala.collection.MapLike.getOrElse$(MapLike.scala:129)
    at scala.collection.AbstractMap.getOrElse(Map.scala:65)
    at sbt.internal.Load$.memoLoadSettingsFile$1(Load.scala:1116)
    at sbt.internal.Load$.$anonfun$discoverProjects$4(Load.scala:1124)
    at scala.collection.immutable.List.map(List.scala:293)
    at sbt.internal.Load$.loadFiles$1(Load.scala:1124)
    at sbt.internal.Load$.discoverProjects(Load.scala:1138)
    at sbt.internal.Load$.discover$1(Load.scala:890)
    at sbt.internal.Load$.loadTransitive(Load.scala:944)
    at sbt.internal.Load$.loadProjects$1(Load.scala:727)
    at sbt.internal.Load$.$anonfun$loadUnit$11(Load.scala:730)
    at sbt.internal.Load$.timed(Load.scala:1385)
    at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:730)
    at sbt.internal.Load$.timed(Load.scala:1385)
    at sbt.internal.Load$.loadUnit(Load.scala:689)
    at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:487)
    at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:180)
    at sbt.internal.BuildLoader.apply(BuildLoader.scala:245)
    at sbt.internal.Load$.loadURI$1(Load.scala:549)
    at sbt.internal.Load$.loadAll(Load.scala:565)
    at sbt.internal.Load$.loadURI(Load.scala:495)
    at sbt.internal.Load$.load(Load.scala:474)
    at sbt.internal.Load$.$anonfun$apply$1(Load.scala:243)
    at sbt.internal.Load$.timed(Load.scala:1385)
    at sbt.internal.Load$.apply(Load.scala:243)
    at sbt.internal.Load$.defaultLoad(Load.scala:56)
    at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:959)
    at sbt.BuiltinCommands$.doLoadProject(Main.scala:959)
    at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:912)
    at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
    at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
    at sbt.Command$.process(Command.scala:189)
    at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
    at scala.Option.getOrElse(Option.scala:189)
    at sbt.MainLoop$.process$1(MainLoop.scala:245)
    at sbt.MainLoop$.processCommand(MainLoop.scala:278)
    at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
    at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
    at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
    at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
    at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
    at sbt.MainLoop$.next(MainLoop.scala:163)
    at sbt.MainLoop$.run(MainLoop.scala:144)
    at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
    at sbt.io.Using.apply(Using.scala:27)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
    at sbt.MainLoop$.runLogged(MainLoop.scala:42)
    at sbt.StandardMain$.runManaged(Main.scala:218)
    at sbt.xMain$.$anonfun$run$11(Main.scala:133)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
    at scala.Console$.withIn(Console.scala:230)
    at sbt.internal.util.Terminal$.withIn(Terminal.scala:560)
    at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:350)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
    at scala.Console$.withOut(Console.scala:167)
    at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:550)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
    at scala.Console$.withErr(Console.scala:196)
    at sbt.internal.util.Terminal$.withOut(Terminal.scala:550)
    at sbt.internal.util.Terminal$.withStreams(Terminal.scala:350)
    at sbt.xMain$.withStreams$1(Main.scala:87)
    at sbt.xMain$.run(Main.scala:121)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:56)
    at sbt.xMain.run(Main.scala:46)
    at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
    at xsbt.boot.Launch$.run(Launch.scala:149)
    at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
    at xsbt.boot.Launch$.launch(Launch.scala:159)
    at xsbt.boot.Launch$.apply(Launch.scala:44)
    at xsbt.boot.Launch$.apply(Launch.scala:21)
    at xsbt.boot.Boot$.runImpl(Boot.scala:78)
    at xsbt.boot.Boot$.run(Boot.scala:73)
    at xsbt.boot.Boot$.main(Boot.scala:21)
    at xsbt.boot.Boot.main(Boot.scala)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at coursier.bootstrap.launcher.a.a(Unknown Source)
    at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
[error] project matching List(PlatformAxis(jvm,JVM,jvm)) and 2.11.12 was not found
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

**Comment by adamw** [comment]
🤦 sorry, indeed there was a bug in the build when sttp_native was disabled (as it is by default). Fixed now :)
