### ISSUE TITLE
Spurious unauthorized after updating

### ISSUE THREAD

**Issue by ckipp01** [scala-steward-org/scala-steward#2332]
Hello! 👋🏼 So this is honestly a bit of a shot in the dark, but throwing this up in _just in case_ you may spot something or have an idea that could give some insight. If not go ahead and close. At work we use Steward and love it ❤️ . Up until recently we've been on 0.9.1 and we just tried bumping to 12 (also tried 11 with the same results). When moving to 12 we started getting failures about not being able to authenticate, but _only_ for very certain repos. We haven't been able to find a pattern in why some of them do and others don't. For example they have the same sbt version, same Scala version, etc.

From what I can tell it happen when it tries to pull down something with sbt, even though it's the same sbt version as one that just worked, since all the failures start the same way:

```
09:31:10  [info] [launcher] getting org.scala-sbt sbt 1.5.5  (this may take some time)...
09:31:10  [info] [launcher] getting Scala 2.12.14 (for sbt)...
09:31:10  [info] welcome to sbt 1.5.5 (Eclipse Foundation Java 11.0.12)
09:31:10  [info] loading global plugins from /root/.sbt/1.0/plugins
09:31:10  [info] compiling 1 Scala source to /root/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes ...
09:31:10  [info] Attempting to fetch org.scala-sbt:compiler-bridge_2.12:1.5.7.
09:31:10  [error] ## Exception when compiling 1 sources to /root/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes
```

We have our sbt creds mounted and they work for other things in the environment, so it'd be odd that they'd be failing here. Looking at the changes between 0.9.1 and 11 there doesn't seem to be anything that raises an alarm to me, but any chance you'd have any idea why this may have started happening when we updated, but not before? I've included a full failure below with debugging turned on. I've tried a lot of things at this point, but before we roll back to avoid the failures I figured I'd ask.

<details>
<summary>Logs of a failure</summary>

```
09:30:37  2021-11-04 08:30:35,688 INFO  ──────────── Steward removed/removed.removed.removed ────────────
09:30:37  2021-11-04 08:30:35,688 INFO  Check cache of removed/removed.removed.removed
09:30:37  2021-11-04 08:30:36,422 INFO  Clone removed/removed.removed.removed
09:30:37  2021-11-04 08:30:36,424 DEBUG Execute GIT_ASKPASS=/opt/scala-steward/pass.sh git -c core.hooksPath=/dev/null clone https://****@removed.removed.removed.com/removed/scm/removed/removed.removed.removed.git /opt/scala-steward/workspace0/repos/removed/removed.removed.removed
09:30:37  2021-11-04 08:30:37,608 DEBUG Execute GIT_ASKPASS=/opt/scala-steward/pass.sh git -c core.hooksPath=/dev/null config user.email ****
09:30:37  2021-11-04 08:30:37,614 DEBUG Execute GIT_ASKPASS=/opt/scala-steward/pass.sh git -c core.hooksPath=/dev/null config user.name Scala Steward
09:30:37  2021-11-04 08:30:37,622 DEBUG Execute GIT_ASKPASS=/opt/scala-steward/pass.sh git -c core.hooksPath=/dev/null submodule update --init --recursive
09:30:37  2021-11-04 08:30:37,652 INFO  Refresh cache of removed/removed.removed.removed
09:30:37  2021-11-04 08:30:37,654 DEBUG Execute GIT_ASKPASS=/opt/scala-steward/pass.sh git -c core.hooksPath=/dev/null rev-parse --abbrev-ref HEAD
09:30:37  2021-11-04 08:30:37,663 DEBUG Execute GIT_ASKPASS=/opt/scala-steward/pass.sh git -c core.hooksPath=/dev/null rev-parse --verify master
09:30:37  2021-11-04 08:30:37,675 INFO  Parsed RepoConfig(CommitsConfig(Some(Scala Steward: update ${artifactName} from ${currentVersion} to ${nextVersion})),PullRequestsConfig(None),ScalafmtConfig(None),UpdatesConfig(List(),List(UpdatePattern(removed.removed,None,None)),List(),None,None),None,None)
09:30:37  2021-11-04 08:30:37,686 DEBUG Execute sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;+ stewardDependencies;reload plugins;stewardDependencies
09:31:10  2021-11-04 08:31:04,897 DEBUG Write /opt/scala-steward/workspace0/store/refresh_error/v1/bitbucket-server/removed/removed.removed.removed/refresh_error.json
09:31:10  2021-11-04 08:31:04,927 ERROR Steward removed/removed.removed.removed failed
09:31:10  java.io.IOException: 'sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 1
09:31:10  copying runtime jar...
09:31:10  [info] [launcher] getting org.scala-sbt sbt 1.5.5  (this may take some time)...
09:31:10  [info] [launcher] getting Scala 2.12.14 (for sbt)...
09:31:10  [info] welcome to sbt 1.5.5 (Eclipse Foundation Java 11.0.12)
09:31:10  [info] loading global plugins from /root/.sbt/1.0/plugins
09:31:10  [info] compiling 1 Scala source to /root/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes ...
09:31:10  [info] Attempting to fetch org.scala-sbt:compiler-bridge_2.12:1.5.7.
09:31:10  [error] ## Exception when compiling 1 sources to /root/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes
09:31:10  [error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
09:31:10  [error] https://nexus-removed.tools.removed.removed.com/repository/maven-public/org/scala-sbt/compiler-bridge_2.12/1.5.7/compiler-bridge_2.12-1.5.7-sources.jar: unauthorized: https://nexus-removed.tools.removed.removed.com/repository/maven-public/org/scala-sbt/compiler-bridge_2.12/1.5.7/compiler-bridge_2.12-1.5.7-sources.jar (Sonatype Nexus Repository Manager)
09:31:10  [error] 
09:31:10  [error] lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:346)
09:31:10  [error] lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
09:31:10  [error] lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
09:31:10  [error] lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:84)
09:31:10  [error] lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
09:31:10  [error] scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
09:31:10  [error] scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
09:31:10  [error] scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
09:31:10  [error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
09:31:10  [error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
09:31:10  [error] java.base/java.lang.Thread.run(Thread.java:829)
09:31:10  [error]            
09:31:10  [error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
09:31:10  [error] https://nexus-removed.tools.removed.removed.com/repository/maven-public/org/scala-sbt/compiler-bridge_2.12/1.5.7/compiler-bridge_2.12-1.5.7-sources.jar: unauthorized: https://nexus-removed.tools.removed.removed.com/repository/maven-public/org/scala-sbt/compiler-bridge_2.12/1.5.7/compiler-bridge_2.12-1.5.7-sources.jar (Sonatype Nexus Repository Manager)
09:31:10  [error] 
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:346)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:84)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
09:31:10  [error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
09:31:10  [error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
09:31:10  [error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
09:31:10  [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
09:31:10  [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
09:31:10  [error] 	at java.base/java.lang.Thread.run(Thread.java:829)
09:31:10  [error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$Unauthorized: unauthorized: https://nexus-removed.tools.removed.removed.com/repository/maven-public/org/scala-sbt/compiler-bridge_2.12/1.5.7/compiler-bridge_2.12-1.5.7-sources.jar (Sonatype Nexus Repository Manager)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.doDownload(Downloader.scala:221)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.$anonfun$remote$2(Downloader.scala:380)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$.$anonfun$downloading$1(Downloader.scala:678)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withUrlLock(CacheLocks.scala:116)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$.helper$2(Downloader.scala:678)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$.coursier$cache$internal$Downloader$$downloading(Downloader.scala:711)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.$anonfun$remote$1(Downloader.scala:380)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:72)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:98)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.remote(Downloader.scala:382)
09:31:10  [error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.$anonfun$remote$5(Downloader.scala:480)
09:31:10  [error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
09:31:10  [error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
09:31:10  [error] 	at scala.util.Success.map(Try.scala:213)
09:31:10  [error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
09:31:10  [error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
09:31:10  [error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
09:31:10  [error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
09:31:10  [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
09:31:10  [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
09:31:10  [error] 	at java.base/java.lang.Thread.run(Thread.java:829)
09:31:10  [error] (Compile / compileIncremental) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
09:31:10  [error] https://nexus-removed.tools.removed.removed.com/repository/maven-public/org/scala-sbt/compiler-bridge_2.12/1.5.7/compiler-bridge_2.12-1.5.7-sources.jar: unauthorized: https://nexus-removed.tools.removed.removed.com/repository/maven-public/org/scala-sbt/compiler-bridge_2.12/1.5.7/compiler-bridge_2.12-1.5.7-sources.jar (Sonatype Nexus Repository Manager)
09:31:10  [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
09:31:10  
09:31:10  	at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:57)
09:31:10  	at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:53)
09:31:10  	at blocking @ org.scalasteward.core.io.process$.$anonfun$slurp$7(process.scala:53)
09:31:10  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
09:31:10  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
09:31:10  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
09:31:10  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
09:31:10  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
09:31:10  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
09:31:10  	at modify @ fs2.internal.Scope.close(Scope.scala:262)
09:31:10  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
09:31:10  	at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:156)
09:31:10  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
09:31:10  	at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1153)
09:31:10  	at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
09:31:10  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
09:31:10  2021-11-04 08:31:04,928 INFO  ──────────── Total time: Steward removed/removed.removed.removed: 29s 239ms ────────────
```
</details>

**Comment by fthomas** [comment]
I've no idea how this error could depend on the Scala Steward version. Scala Steward shells out to sbt to get the list of dependencies. This log
```
09:31:10  [info] welcome to sbt 1.5.5 (Eclipse Foundation Java 11.0.12)
09:31:10  [info] loading global plugins from /root/.sbt/1.0/plugins
09:31:10  [info] compiling 1 Scala source to /root/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes ...
09:31:10  [info] Attempting to fetch org.scala-sbt:compiler-bridge_2.12:1.5.7.
09:31:10  [error] ## Exception when compiling 1 sources to /root/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes
```
shows that sbt fails during startup while compiling a global plugin in `/root/.sbt/1.0/plugins`. This plugin is probably [`StewardPlugin.scala`](https://github.com/scala-steward-org/scala-steward/blob/58e2d0df4a2a8df5422c0af1a02d380c83ea6482/modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala) which Scala Steward copies into `/root/.sbt/1.0/plugins` when it starts. Maybe the credentials also need to be mounted somewhere else where sbt can find them while compiling global plugins?

**Comment by ckipp01** [comment]
> I've no idea how this error could depend on the Scala Steward version.

My thoughts exactly. 

> Maybe the credentials also need to be mounted somewhere else where sbt can find them while compiling global plugins?

I'll try to look more into this.

The odd thing is that I would expect this to fail for everything, not just for one. Who knows. Thanks for taking a look!
