### ISSUE TITLE
Scala Steward container exits silently

### ISSUE THREAD

**Issue by stingster** [scala-steward-org/scala-steward#2579]
I am trying to run a Scala Steward image in a container with the next options:

`docker run -v $PWD:/opt/scala-steward -i fthomas/scala-steward:0.14.0 --disable-sandbox --do-not-fork --workspace /opt/scala-steward/workspace --repos-file "/opt/scala-steward/repos.md" --git-ask-pass /opt/scala-steward/token.sh --git-author-email "steward" --git-author-name "steward" --vcs-type "gitlab"  --vcs-login "x-auth-token" --vcs-api-host "https://git.datcon.co.uk/api/v4/"`

After logging:

`2022-04-20 08:03:40,687 INFO   
  ____            _         ____  _                             _
 / ___|  ___ __ _| | __ _  / ___|| |_ _____      ____ _ _ __ __| |
 \___ \ / __/ _` | |/ _` | \___ \| __/ _ \ \ /\ / / _` | '__/ _` |
  ___) | (_| (_| | | (_| |  ___) | ||  __/\ V  V / (_| | | | (_| |
 |____/ \___\__,_|_|\__,_| |____/ \__\___| \_/\_/ \__,_|_|  \__,_|
 v0.14.0
 
2022-04-20 08:03:41,533 INFO  Loaded 55 artifact migration(s)
2022-04-20 08:03:41,712 INFO  Loaded 26 Scalafix migration(s)
2022-04-20 08:03:41,828 INFO  Loaded 1 repo config(s)
2022-04-20 08:03:42,065 INFO  Run self checks
2022-04-20 08:03:42,074 INFO  Using git version 2.32.0
2022-04-20 08:03:42,600 INFO  Using scalafix 0.9.34
2022-04-20 08:03:43,265 INFO  Using scalafmt 3.3.3
2022-04-20 08:03:43,795 INFO  Clean workspace /opt/scala-steward/workspace
2022-04-20 08:03:43,802 INFO  Add global sbt plugins
2022-04-20 08:03:43,865 INFO  ──────────── Total time: run: 1s 797ms ────────────`

it just exits without any additional info.

I believe that in case of failure it should log something useful so that we can debug the problem.

Thanks for you understanding.

**Comment by gervaisb** [comment]
Same issue with Gitlab on-premise. I have added the `-DLOG_LEVEL=DEBUG` option and cannot see anything wrong. 
@stingster did you find a solution?

The difference that I have is that there is only one project so I have configured Scalasteward on the project itself. That's why I `echo "$CI_PROJECT_PATH" > "$CI_PROJECT_DIR/repos.md"` at the beginning of the script. 

[scalasteward.logs.txt](https://github.com/scala-steward-org/scala-steward/files/8629436/scalasteward.logs.txt)

**Comment by mzuehlke** [comment]
@gervaisb sadly the logging in that part is not that verbose, but
the `repos.md` file must have the following format `- ORG/REPO(:BRANCH)` 
see: https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/scala/org/scalasteward/core/vcs/data/Repo.scala#L37

**Comment by gervaisb** [comment]
Indeed, having an error message about the `repos.md` format would have been useful. Everything seems good now, at least I have a lot of new MRs. 🎉 

However there are some exceptions in the logs, but the MRs are created. I guess it print them because I have activated the DEBUG log.

```
2022-05-05 08:43:42,214 INFO  Create PR update/scalafmt-core-3.5.2
2022-05-05 08:43:49,807 DEBUG Execute GIT_ASKPASS=/builds/organisation/organisation-backend/pass.sh git -c core.hooksPath=/dev/null grep -I --fixed-strings --files-with-matches 2.7.5
java.io.IOException: 'GIT_ASKPASS=/builds/organisation/organisation-backend/pass.sh git -c core.hooksPath=/dev/null grep -I --fixed-strings --files-with-matches 2.7.5' exited with code 1
	at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:54)
	at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:50)
	at blocking @ org.scalasteward.core.io.FileAlg$$anon$1.ensureExists(FileAlg.scala:100)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at modify @ fs2.internal.Scope.close(Scope.scala:262)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:156)
	at get @ fs2.internal.Scope.openScope(Scope.scala:281)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:932)
	at get @ fs2.internal.Scope.openScope(Scope.scala:281)
2022-05-05 08:43:50,899 DEBUG Write /builds/organisation/organisation-backend/workspace/store/pull_requests/v2/gitlab/organisation/organisation-backend/pull_requests.json
2022-05-05 08:43:50,900 INFO  Created PR https://gitlab.our.private.instance/organisation/organisation-backend/-/merge_requests/146
```

**Comment by mzuehlke** [comment]
That DEBUG output is there, because `git grep` doesn't find a match and has an exit code of 1.

**Comment by gervaisb** [comment]
Okay. Then the issue is solved for my part. Thanks.

**Comment by fthomas** [comment]
I think this exception is printed because of some change in a recent cats-effect update. We're not printing this exception on purpose.
