### ISSUE TITLE
Failed to load artifact migration (artifact-migrations.v2.conf)

### ISSUE THREAD

**Issue by xerial** [scala-steward-org/scala-steward#2616]
Recently, scala-steward starts failing when reading artifact-migrations.v2.conf file (an example [GitHub Action run](https://github.com/xerial/scala-steward-repos/runs/6698874751?check_suite_focus=true)): 
```
  Error: java.lang.Throwable: Failed to load artifact migrations from https://raw.githubusercontent.com/scala-steward-org/scala-steward/master/modules/core/src/main/resources/artifact-migrations.v2.conf
  Error: 	at org.scalasteward.core.update.artifact.ArtifactMigrationsLoader$$anonfun$decodeMigrations$1.applyOrElse(ArtifactMigrationsLoader.scala:50)
  Error: 	at org.scalasteward.core.update.artifact.ArtifactMigrationsLoader$$anonfun$decodeMigrations$1.applyOrElse(ArtifactMigrationsLoader.scala:50)
  Error: 	at scala.PartialFunction$AndThen.applyOrElse(PartialFunction.scala:288)
  Error: 	at cats.ApplicativeError.$anonfun$recoverWith$1(ApplicativeError.scala:130)
  Error: 	at recoverWith$extension @ org.scalasteward.core.io.process$.$anonfun$slurp$3(process.scala:63)
  Error: 	at blocking @ org.scalasteward.core.io.FileAlg$$anon$1.ensureExists(FileAlg.scala:100)
  Error: 	at blocking @ org.scalasteward.core.io.FileAlg$$anon$1.ensureExists(FileAlg.scala:100)
  Error: 	at blocking @ org.scalasteward.core.io.FileAlg$$anon$1.ensureExists(FileAlg.scala:100)
  Error: 	at make @ org.http4s.okhttp.client.OkHttpBuilder$.defaultOkHttpClient(OkHttpBuilder.scala:202)
  Error: 	at make @ org.http4s.okhttp.client.OkHttpBuilder$.defaultOkHttpClient(OkHttpBuilder.scala:202)
  Error: 	at flatMap @ org.scalasteward.core.update.artifact.ArtifactMigrationsLoader.$anonfun$loadMigrations$2(ArtifactMigrationsLoader.scala:46)
  Error: 	at map @ org.scalasteward.core.update.artifact.ArtifactMigrationsLoader.$anonfun$loadMigrations$2(ArtifactMigrationsLoader.scala:46)
  Error: Caused by: DecodingFailure(Attempt to decode value on failed cursor, List(DownField(artifactIdAfter), MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, DownArray, DownField(changes)))
Error:  ✕ Launching org.scala-steward:scala-steward-core_2.13:0.14.0 failed
```

There might be invalid migration configurations or the default branch name change from master -> main might be related if the http client needs to follow 3xx redirect response.

I suspect recent change #2615 has an issue

**Comment by xerial** [comment]
#2617 was not sufficient. #2618 fixed this issue.

**Comment by bpholt** [comment]
Oops, sorry folks. Thanks for fixing it.
