### ISSUE TITLE
BSP?

### ISSUE THREAD

**Issue by Fristi** [scala-steward-org/scala-steward#2640]
Could scala-steward work with BSP? 

This would enable maybe support for Bazel aswell?

**Comment by fthomas** [comment]
Btw, I think it would be super cool if Scala Steward could leverage BSP and work with any BSP implementing build tools out of the box. I imagine that it would also be a fun project to work on.

**Comment by fthomas** [comment]
It is not surprising that the `buildTarget/dependencyModules` call does not return a response. Calling `build/initialize`
```shell
echo '{ "jsonrpc": "2.0", "id": 1, "method": "build/initialize", "params": { "displayName": "test", "version": "0", "bspVersion": "1.0", "rootUri": "file:/home/frank/data/code/scala-steward/core/", "capabilities": { "languageIds": [] } } }' | \
  nc -U /home/frank/.sbt/1.0/server/1d64d996d87d4bc7b927/sock
```
returns sbt's current BSP capabilities:
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "displayName": "sbt",
    "version": "1.7.0-RC2",
    "bspVersion": "2.0.0-M5",
    "capabilities": {
      "compileProvider": ...,
      "testProvider": ...,
      "runProvider": ...,
      "dependencySourcesProvider": true,
      "resourcesProvider": true,
      "canReload": true,
      "jvmRunEnvironmentProvider": true,
      "jvmTestEnvironmentProvider": true
    }
  }
}
```
and it is missing a `"dependencyModulesProvider": true` which would indicate that `buildTarget/dependencyModules` is supported.

**Comment by Fristi** [comment]
Weird, is it possible to set sbt with debugging on BSP ?

**Comment by fthomas** [comment]
Maybe. My current understanding is that `buildTarget/dependencyModules` is just not supported by sbt. But I haven't checked the sbt sources if that is actually the case.

**Comment by fthomas** [comment]
Ok, checked it. This method is currently not supported: https://github.com/sbt/sbt/blob/1.7.x/main/src/main/scala/sbt/internal/server/BuildServerProtocol.scala#L314-L332

**Comment by Fristi** [comment]
It seems to be supported by bazel-bsp though https://github.com/JetBrains/bazel-bsp/blob/master/server/src/main/java/org/jetbrains/bsp/bazel/server/bsp/BspServerApi.java#L158

**Comment by fthomas** [comment]
I had a little chat with Mill about https://github.com/scala-steward-org/test-repo-2 via BSP:
```
$ /home/frank/.cache/mill/download/0.10.5 --bsp --disable-ticker --color false --jobs 1

Content-Length: 240

{ "jsonrpc": "2.0", "id": 1, "method": "build/initialize", "params": { "displayName": "test", "version": "0", "bspVersion": "1.0", "rootUri": "file:/home/frank/data/code/scala-steward/test-repo-2", "capabilities": { "languageIds": [] } } }

Content-Length: 538

{"jsonrpc":"2.0","id":1,"result":{"displayName":"mill-bsp","version":"0.10.5","bspVersion":"2.0.0","capabilities":{"compileProvider":{"languageIds":["java","scala"]},"testProvider":{"languageIds":["java","scala"]},"runProvider":{"languageIds":["java","scala"]},"debugProvider":{"languageIds":[]},"inverseSourcesProvider":true,"dependencySourcesProvider":true,"dependencyModulesProvider":true,"resourcesProvider":true,"buildTargetChangedProvider":false,"jvmRunEnvironmentProvider":true,"jvmTestEnvironmentProvider":true,"canReload":true}}}

Content-Length: 80

{ "jsonrpc": "2.0", "id": 0, "method": "workspace/buildTargets", "params": {} }

Content-Length: 2256

{"jsonrpc":"2.0","id":0,"result":{"targets":[{"id":{"uri":"file:///home/frank/data/code/scala-steward/test-repo-2/hello?id\u003dhello"},"displayName":"hello","baseDirectory":"file:///home/frank/data/code/scala-steward/test-repo-2/hello","tags":["library","application"],"languageIds":["java","scala"],"dependencies":[],"capabilities":{"canCompile":true,"canTest":false,"canRun":true,"canDebug":false},"dataKind":"scala","data":{"scalaOrganization":"org.scala-lang","scalaVersion":"2.13.1","scalaBinaryVersion":"2.13","platform":1,"jars":["file:///home/frank/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.1/scala-compiler-2.13.1.jar","file:///home/frank/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.1/scala-reflect-2.13.1.jar","file:///home/frank/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar","file:///home/frank/.cache/coursier/v1/https/repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar","file:///home/frank/.cache/coursier/v1/https/repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.12/jansi-1.12.jar"]}},{"id":{"uri":"file:///home/frank/data/code/scala-steward/test-repo-2?id\u003dmill-build"},"displayName":"mill-build","baseDirectory":"file:///home/frank/data/code/scala-steward/test-repo-2","tags":["library","application"],"languageIds":["scala"],"dependencies":[],"capabilities":{"canCompile":false,"canTest":false,"canRun":false,"canDebug":false},"dataKind":"scala","data":{"scalaOrganization":"org.scala-lang","scalaVersion":"2.13.8","scalaBinaryVersion":"2.13","platform":1,"jars":["file:///home/frank/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.8/scala-compiler-2.13.8.jar","file:///home/frank/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.8/scala-reflect-2.13.8.jar","file:///home/frank/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar","file:///home/frank/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.21.0/jline-3.21.0.jar","file:///home/frank/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar"]}}]}}

Content-Length: 186

{ "jsonrpc": "2.0", "id": 1, "method": "buildTarget/dependencyModules", "params": { "targets": [{"uri":"file:///home/frank/data/code/scala-steward/test-repo-2/hello?id\u003dhello"}] } }

Content-Length: 261

{"jsonrpc":"2.0","id":1,"result":{"items":[{"target":{"uri":"file:///home/frank/data/code/scala-steward/test-repo-2/hello?id\u003dhello"},"modules":[{"name":"eu.timepit:refined","version":"0.10.1"},{"name":"org.scala-lang:scala-library","version":"2.13.1"}]}]}}
```
What's great here is that Mill responded with the library dependencies `"modules":[{"name":"eu.timepit:refined","version":"0.10.1"},{"name":"org.scala-lang:scala-library","version":"2.13.1"}]` in the response to the `buildTarget/dependencyModules` call. Unfortunately the resolvers for these dependencies are not included. Scala Steward needs to know where to check for new versions of these dependencies.

**Comment by Fristi** [comment]
Nice going! I like it that mill already supports this, but I guess also IDE devs would encouter this issue of not being able to resolve these depenencies? I wonder how they do this.

If BSP is fully supported by mill, sbt, bazel, maven, gradle then scala-steward could work for all of these

**Comment by fthomas** [comment]
My guess is that resolvers are not currently part of BSP because IDEs do not require them and they let the build tools do the resolution. Maybe we should ask the BSP maintainers if adding resolvers (+ credentials) to the protocol would be possible or if it is out of scope.

**Comment by Fristi** [comment]
Created a proposal https://github.com/build-server-protocol/build-server-protocol/issues/344

**Comment by adpi2** [comment]
This is a cool project. Another build tool that supports BSP is scala-cli.

**Comment by fthomas** [comment]
To make things a little bit more concrete let's have a look at the information Scala Steward currently gets from sbt via the [`stewardDependencies`](https://github.com/scala-steward-org/scala-steward/blob/c17d36778448a6fde2d38254f5806af6ca927241/modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala) task that Scala Steward injects into the sbt build. The output of that task looks like this:
https://github.com/scala-steward-org/scala-steward/blob/c17d36778448a6fde2d38254f5806af6ca927241/modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/parserTest.scala#L18-L31
Each line in the output is either a dependency or a resolver or garbage that is ignored. What is notable here is that the artifactIds have a name as written in the build file and a name plus Scala binary suffix if it is a declared with `%%` or `%%%` The latter is used to find the versions of that dependency from the resolvers. For sbt plugins there are also the `sbtVersion` and `scalaVersion` attributes that are passed to Coursier for resolution. To get all dependencies for all Scala versions in the build, Scala Steward calls the aforementioned task as `+ stewardDependencies`.

If we get more or less the same information via BSP, Scala Steward could work with all BSP compliant build tools out of the box or with minimal effort.

**Comment by fthomas** [comment]
I think we can build a prototype for BSP support using Mill even if we currently don't get the resolvers from the build server. We could just use Maven Central as resolver for all reported dependencies and hope that the protocol will be extended in the future. The workflow in Scala Steward acting as a BSP client would then look like this:

- discover the build tool used in a project

- run the command of the discovered build tool to generate the BSP connection details

  - sbt: `$ sbt bspConfig` creates the connection details in `.bsp/sbt.json`
  
  - Mill: `$ mill mill.bsp.BSP/install` creates the connection details in `.bsp/mill-bsp.json`

- use the connection details to start and connect to the BSP server

- call [`build/initialize`](https://build-server-protocol.github.io/docs/specification#initialize-build-request) to initialize the build

- call [`workspace/buildTargets`](https://build-server-protocol.github.io/docs/specification#workspace-build-targets-request) to get a list of build targets

- call [`buildTarget/dependencyModules`](https://build-server-protocol.github.io/docs/specification#dependency-modules-request) with all build targets from the previous response as parameters to get all dependencies of the build

- call [`build/shutdown`](https://build-server-protocol.github.io/docs/specification#shutdown-build-request) to prepare shutdown of the build server

- call [`build/exit`](https://build-server-protocol.github.io/docs/specification#exit-build-notification) to exit the build server

**Comment by fthomas** [comment]
I have a working prototype that implements the above workflow and talks to Mill at https://github.com/scala-steward-org/scala-steward/compare/wip/bsp.

Extracting dependencies from the `buildTarget/dependencyModules` currently works for Java dependencies but not for Scala dependencies. This is illustrated by these two dependencies in the response:
```
modules = ArrayList (
  DependencyModule [
    name = "eu.timepit:refined"
    version = "0.10.1"
    dataKind = null
    data = null
  ],
  DependencyModule [
    name = "ch.epfl.scala:bsp4j"
    version = "2.1.0-M3"
    dataKind = null
    data = null
  ],
  ...
```
These correspond to this definition in the build: https://github.com/scala-steward-org/test-repo-2/blob/4b70c7459a2d47427c6738e811306a3cdaa4de1b/build.sc#L24-L27

`eu.timepit:refined` is actually a Scala library and its exact artifactId is `refined_2.13`. So Mill is only telling us the artifactId as written in the build without the Scala binary suffix but Scala Steward requires the exact artifactId to look up available versions in the appropriate resolvers. bsp4j is a pure Java dependency and has no additional suffix, Scala Steward is able to extract and find its latest version and update it (which it did in https://github.com/scala-steward-org/test-repo-2/pull/176).

There are at least two options how Mill could report the exact artifactId in the above `DependencyModule`:
1. Change the `name` field such that includes the exact artifactId and not the name that is used in the build, e.g.: `name = "eu.timepit:refined_2.13"`
2. Use the optional `DependencyModule#data` field to include a [`MavenDependencyModule`](https://build-server-protocol.github.io/docs/extensions/maven) which has separate fields for the organization and name (artifactId) which could use the exact artifactId.

The BSP is not very specific in these cases which values are expected in these fields. I'll look into Mill and see if we can change the implementation such that exact artifactIds are used.

**Comment by fthomas** [comment]
Tried this prototype with a [simple Bazel project](https://github.com/scala-steward-org/test-repo-2/tree/bazel) but unfortunately `bazelbsp` is not yet a dependency modules provider (`dependencyModulesProvider = null`).

**Comment by lefou** [comment]
> There are at least two options how Mill could report the exact artifactId in the above `DependencyModule`:
> 
>     1. Change the `name` field such that includes the exact artifactId and not the name that is used in the build, e.g.: `name = "eu.timepit:refined_2.13"`
> 
>     2. Use the optional `DependencyModule#data` field to include a [`MavenDependencyModule`](https://build-server-protocol.github.io/docs/extensions/maven) which has separate fields for the organization and name (artifactId) which could use the exact artifactId.
> 
> 
> The BSP is not very specific in these cases which values are expected in these fields. I'll look into Mill and see if we can change the implementation such that exact artifactIds are used.

I think option 1. is the most straight forward one.

**Comment by lefou** [comment]
@fthomas Can you test against Mill `0.11.0-M3` or the latest `main` branch? In `0.11` we change how we handle transitive dependencies and resolve platform and Scala versions earlier, so there is a good chance, that Mill 0.11 already reports the correct full artifactId.

**Comment by fthomas** [comment]
Just tested it with 0.11.0-M3:
```
[info]         DependencyModule [
[info]           name = "eu.timepit:refined_2.13"
[info]           version = "0.10.1"
[info]           dataKind = null
[info]           data = null
[info]         ],
[info]         DependencyModule [
[info]           name = "ch.epfl.scala:bsp4j"
[info]           version = "2.1.0-M4"
[info]           dataKind = null
[info]           data = null
[info]         ],
```
This is awesome, @lefou! Thank you!

The only thing missing now on the BSP side are the resolvers.

**Comment by romanowski** [comment]
A shameless plug: we have just released the first stable version of [Bazel Stward](https://virtuslab.github.io/bazel-steward/) - a bot similar to Scala Stward but dedicated to Bazel.

The BSP-based approach discussed there should have much wider usage than Bazel (e.g. [Bleep](https://bleep.build/docs/)) but for now, Bazel Stward may be a good option for Bazel users.

**Comment by fthomas** [comment]
FYI: [BspServerType.scala](https://github.com/scala-steward-org/scala-steward/blob/e5e5dadb84f346ecb1b46c2bfd7369e115d029fe/modules/core/src/main/scala/org/scalasteward/core/buildtool/bsp/BspServerType.scala) on the [wip/bsp](https://github.com/scala-steward-org/scala-steward/tree/wip/bsp) branch now lists BSP servers that are known to Scala Steward and if they can be used to extract dependencies. Currently only Mill reports dependencies via `buildTarget/dependencyModules` but I believe that Scala CLI and bleep should be able to do that too once they are updated to the latest Bloop version.

**Comment by Arthurm1** [comment]
@fthomas If you're still looking to add Gradle BSP, I have published a fork of [Microsoft's Build Server](https://github.com/Arthurm1/build-server-for-gradle)

You can see if it works for you in `BspServerType.scala` using...
```scala
connectionDetailsCommand = Nel.of(
    "cs",
    "launch",
    "io.github.arthurm1.gradle.bsp:server:0.7.0",
    "-r", "https://repo.gradle.org/gradle/libs-releases",
    "-M", "com.microsoft.java.bs.core.Launcher"
)
```

**Comment by fthomas** [comment]
That's great @Arthurm1!

I tried running this command in the root of https://github.com/scala-steward-org/test-repo-1/tree/gradle-test but it did not create a [BSP connection file](https://build-server-protocol.github.io/docs/overview/server-discovery#the-bsp-connection-details). It seems this command starts the BSP server, right?

If I use it to start the BSP server, `buildInitialize` succeeds and returns
```
InitializeBuildResult [
   displayName = "gradle-build-server"
   version = "0.7.0"
   bspVersion = "2.2.0-M2"
   capabilities = BuildServerCapabilities [
     compileProvider = CompileProvider [
       languageIds = ArrayList (
         "java",
         "scala",
         "groovy",
         "kotlin"
       )
     ]
     testProvider = TestProvider [
       languageIds = ArrayList (
         "java",
         "scala",
         "groovy",
         "kotlin"
       )
     ]
     runProvider = RunProvider [
       languageIds = ArrayList (
         "java",
         "scala",
         "groovy",
         "kotlin"
       )
     ]
     debugProvider = null
     inverseSourcesProvider = true
     dependencySourcesProvider = true
     dependencyModulesProvider = true
     resourcesProvider = true
     outputPathsProvider = true
     buildTargetChangedProvider = true
     jvmRunEnvironmentProvider = true
     jvmTestEnvironmentProvider = true
     canReload = true
   ]
   data = {"isWrapperEnabled":true}
 ]
```
But the subsequent `workspaceBuildTargets` call then fails with
```
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209
```

**Comment by Arthurm1** [comment]
@fthomas Ah my bad.  I didn't realise the job of the `BspServerType` was to create a `.bsp` file.  I thought it was to start the server.

I'll look to add a way to create the file.

Not sure why `workspaceBuildTargets` is failing - I'm testing it against `Metals` and that seems to be fine.  Do you have the full stacktrace  - maybe it's expecting something in your `build/initialize` that's not there and causing issues later in the code.

**Comment by fthomas** [comment]
`build/initialize` is called with
```
InitializeBuildParams [
  displayName = "Scala Steward"
  version = "0.28.0-75-cf26eca2-20250217-2201-SNAPSHOT"
  bspVersion = "2.1.1"
  rootUri = "file:///home/frank/data/code/scala-steward/core/workspace/repos/scala-steward-org/test-repo-1/"
  capabilities = BuildClientCapabilities [
    languageIds = EmptyList ()
  ]
  dataKind = null
] 
```
and the full stack trace is
```
 org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at fromCompletableFuture @ org.http4s.jdkhttpclient.JdkHttpClient$.$anonfun$apply$23(JdkHttpClient.scala:243)
 	at onError$extension @ org.scalasteward.core.buildtool.bsp.BspExtractor.lift(BspExtractor.scala:132)
 	at map @ org.scalasteward.core.buildtool.bsp.BspExtractor.$anonfun$getBspDependencies$13(BspExtractor.scala:108)
 	at flatMap @ org.scalasteward.core.buildtool.bsp.BspExtractor.$anonfun$getBspDependencies$13(BspExtractor.scala:108)
 	at map @ org.scalasteward.core.buildtool.bsp.BspExtractor.$anonfun$getBspDependencies$10(BspExtractor.scala:104)
 	at flatMap @ org.scalasteward.core.buildtool.bsp.BspExtractor.$anonfun$getBspDependencies$10(BspExtractor.scala:104)
 	at map @ org.scalasteward.core.buildtool.bsp.BspExtractor.$anonfun$getBspDependencies$6(BspExtractor.scala:99)
 	at flatMap @ org.scalasteward.core.buildtool.bsp.BspExtractor.$anonfun$getBspDependencies$6(BspExtractor.scala:99)
```
I also tried setting `capabilities` in `InitializeBuildParams` to
```
   capabilities = BuildClientCapabilities [
     languageIds = SingletonList (
       "scala"
     )
   ]
```
but this also results in the above error.

**Comment by Arthurm1** [comment]
@fthomas I think I've fixed the `internal error` issue and I've added the bsp file creation.

Could you now try...
```scala
case object Gradle
    extends BspServerType(
      connectionDetailsCommand = Nel.of(
        "cs",
        "launch",
        "io.github.arthurm1.gradle.bsp:server:0.8.0",
        "-r", "https://repo.gradle.org/gradle/libs-releases",
        "-M", "com.microsoft.java.bs.core.BspFileCreator"
      ),
      connectionDetailsName = "gradle-bsp.json"
    )
```

**Comment by fthomas** [comment]
@Arthurm1 I just tried it. The `gradle-bsp.json` is generated but it uses `java.exe` as name for the Java executable. Since I'm on Linux, my Java executable is just called `java`.

**Comment by Arthurm1** [comment]
@fthomas Could you up the version number from `0.8.0` to `0.11.0` and try again?

**Comment by Arthurm1** [comment]
@fthomas Did this work in the end?  Was it a viable solution?

Another option is to run the following in the Gradle project directory...
```
coursier launch io.github.arthurm1.gradle.bsp:server:0.12.0 -r https://repo.gradle.org/gradle/libs-releases -M com.microsoft.java.bs.core.BloopExporter
```

This will output [Bloop](https://scalacenter.github.io/bloop/docs/assets/bloop-schema.json) files into the `.bloop` dir.  There will be a `json` file per source set and the `project/resolution/modules` section will contain the libraries.
