### ISSUE TITLE
`java.io.IOException: Cannot run program "scala-cli"`

### ISSUE THREAD

**Issue by armanbilge** [scala-steward-org/scala-steward#2948]
I'm a little puzzled what's going on 🤔 

https://github.com/typelevel/steward/actions/runs/4034855994/jobs/6936380468

```
2023-01-29 03:14:57,119 ERROR Steward typelevel/cats-effect:series/3.x failed
  java.io.IOException: Cannot run program "scala-cli" (in directory "/home/runner/scala-steward/workspace/repos/typelevel/cats-effect"): error=2, No such file or directory
  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
  	at org.scalasteward.core.io.process$.$anonfun$createProcess$5(process.scala:81)
  	at flatMap @ org.scalasteward.core.io.process$.createProcess(process.scala:79)
  	at flatMap @ org.scalasteward.core.io.process$.slurp(process.scala:43)
  	at delay @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.isDebugEnabled(Slf4jLoggerInternal.scala:65)
  	at ifM$extension @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.info(Slf4jLoggerInternal.scala:91)
  	at >>$extension @ org.scalasteward.core.io.ProcessAlg$.$anonfun$create$1(ProcessAlg.scala:92)
  	at map @ org.scalasteward.core.buildtool.scalacli.ScalaCliAlg.$anonfun$getDependencies$2(ScalaCliAlg.scala:54)
  	at flatMap @ org.scalasteward.core.buildtool.scalacli.ScalaCliAlg.$anonfun$getDependencies$2(ScalaCliAlg.scala:54)
  	at map @ org.scalasteward.core.buildtool.scalacli.ScalaCliAlg.getDependencies(ScalaCliAlg.scala:50)
  	at flatMap @ org.scalasteward.core.buildtool.scalacli.ScalaCliAlg.getDependencies(ScalaCliAlg.scala:50)
  	at delay @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.$anonfun$info$4(Slf4jLoggerInternal.scala:91)
  	at delay @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.isInfoEnabled(Slf4jLoggerInternal.scala:66)
  	at ifM$extension @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.info(Slf4jLoggerInternal.scala:91)
  	at >>$extension @ org.scalasteward.core.io.ProcessAlg$.$anonfun$create$1(ProcessAlg.scala:92)
  Caused by: java.io.IOException: error=2, No such file or directory
  	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
  	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
  	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
  	at org.scalasteward.core.io.process$.$anonfun$createProcess$5(process.scala:81)
  	at cats.effect.unsafe.WorkerThread.blockOn(WorkerThread.scala:631)
  	at scala.concurrent.package$.blocking(package.scala:124)
  	at cats.effect.IOFiber.runLoop(IOFiber.scala:953)
  	at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1325)
  	at cats.effect.IOFiber.run(IOFiber.scala:119)
  	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:585)
  2023-01-29 03:14:57,126 INFO  ──────────── Total time: Steward typelevel/cats-effect:series/3.x: 1m 32s 74ms 
```

**Comment by armanbilge** [comment]
Oh, is this recursive? We have some scala-cli examples in the docs with `//> using lib`.

https://github.com/scala-steward-org/scala-steward/blob/f44b48c2cea0ab8c56e3af12cf2cec6414bee2e9/modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala#L42-L47

**Comment by fthomas** [comment]
> Oh, is this recursive?

Yes, it is. It would be nice if there were an easier way to know if a project uses Scala CLI.

> We have some scala-cli examples in the docs with `//> using lib`.

Like https://github.com/typelevel/cats-effect/blob/v3.4.5/docs/faq.md. In this case we could check that the files found by
by the above code is a `.scala` or `.sc` file.

**Comment by fthomas** [comment]
Or maybe not: https://scala-cli.virtuslab.org/docs/commands/basics#source-files. Scala CLI also considers `.md` files as source files:

> Scala CLI accepts the following types of source code:
> 
>     .scala files, containing Scala code
>     .sc files, containing Scala scripts (see more in the [Scripts guide](https://scala-cli.virtuslab.org/docs/guides/scripts))
>     .java files, containing Java code
>     .md files, containing Markdown code (experimental, see more in the [Markdown guide](https://scala-cli.virtuslab.org/docs/guides/markdown))
>     .c and .h files, containing C code (only as resources for Scala Native, see more in the [Scala Native guide](https://scala-cli.virtuslab.org/docs/guides/scala-native))
>     .jar files, (see more in the [Run docs](https://scala-cli.virtuslab.org/docs/commands/run#jar))

**Comment by fthomas** [comment]
> In this case we could check that the files found by the above code is a `.scala` or `.sc` file.

I now think we should do this. Concluding from Scala CLI examples in Markdown files that a project uses Scala CLI  seem to do more harm than good.

**Comment by alejandrohdezma** [comment]
I'm wondering if the `scala-steward-action` should install `scala-cli` as we do with `scalafix` or `scalafmt`. WDYT @fthomas?

**Comment by fthomas** [comment]
@alejandrohdezma That sounds like a good idea. Scala Steward treats `scala-cli` similar to `mvn`, `mill`, and `sbt`. If it detects that a project has a Scala CLI, Maven, Mill, or sbt build, it runs that tool to extract dependencies from their builds. If the `scala-steward-action` provides it out of the box, that will definitely make it easier for users.

**Comment by alejandrohdezma** [comment]
@fthomas @armanbilge [this PR](https://github.com/scala-steward-org/scala-steward-action/pull/465) should fix it

**Comment by alejandrohdezma** [comment]
@armanbilge It has been merged so `typelevel-steward` should work again if you are using `v2`

**Comment by armanbilge** [comment]
Thanks! I guess we can close this issue? Or will we go ahead with https://github.com/scala-steward-org/scala-steward/pull/2971 as well?
