### ISSUE TITLE
java.io.IOException unable to sign with scala-steward-action

### ISSUE THREAD

**Issue by egaxhaj** [scala-steward-org/scala-steward#2952]
I've set up a scala-steward workflow to sign commits but I am getting the below error and am unable to debug. All the keys are found and loaded correctly but it is unable to sign and errors out with ` java.io.IOException`

If this needs to be on the `scala-steward-action` repo here's the ticket I open two weeks back https://github.com/scala-steward-org/scala-steward-action/issues/455.

```
Run scala-steward-org/scala-steward-action@v2
  with:
    github-token: ***
    signing-key: ...
    sign-commits: true
    author-email: ...
    author-name: Affine Health
    ignore-opts-files: true
    cache-ttl: 2hours
    coursier-cli-url: https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz
    github-api-url: https://api.github.com
    github-app-auth-only: false
    github-repository: affinehealth/ProviderData
    mill-version: 0.10.9
    repo-config: .github/.scala-steward.conf
    timeout: 20min
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.17-8/x64
    JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.17-8/x64

... 

Launching scala-steward
 2023-01-16 21:45:00,425 INFO   
   ____            _         ____  _                             _
  / ___|  ___ __ _| | __ _  / ___|| |_ _____      ____ _ _ __ __| |
  \___ \ / __/ _` | |/ _` | \___ \| __/ _ \ \ /\ / / _` | '__/ _` |
   ___) | (_| (_| | | (_| |  ___) | ||  __/\ V  V / (_| | | | (_| |
  |____/ \___\__,_|_|\__,_| |____/ \__\___| \_/\_/ \__,_|_|  \__,_|
  v0.20.0
  
 2023-01-16 21:45:01,710 INFO  Loaded 101 artifact migration(s)
 2023-01-16 21:45:01,902 INFO  Loaded 30 Scalafix migration(s)
 2023-01-16 21:45:02,005 INFO  Loaded 1 repo config(s)
 2023-01-16 21:45:02,335 INFO  Run self checks
 2023-01-16 21:45:02,349 INFO  Using git version 2.39.0
 2023-01-16 21:45:03,031 INFO  Using scalafix 0.10.4
 2023-01-16 21:45:03,770 INFO  Using scalafmt 3.6.1
 2023-01-16 21:45:04,124 INFO  Clean /home/runner/scala-steward/workspace/repos
 2023-01-16 21:45:04,172 INFO  ──────────── Steward affinehealth/ProviderData ────────────
 2023-01-16 21:45:04,175 INFO  Check cache of affinehealth/ProviderData
 2023-01-16 21:45:04,729 INFO  Find updates for affinehealth/ProviderData
 2023-01-16 21:45:06,323 INFO  Ignore com.typesafe.slick:(slick, slick_2.12) : 3.4.1 -> 3.5.0-M1 (reason: no suitable next version)
 2023-01-16 21:45:06,324 INFO  Ignore com.typesafe.slick:(slick-hikaricp, slick-hikaricp_2.12) : 3.4.1 -> 3.5.0-M1 (reason: no suitable next version)
 2023-01-16 21:45:06,441 INFO  Found 12 updates:
   io.netty:netty-all : 4.1.50.Final -> 4.1.87.Final
   org.scalactic:(scalactic, scalactic_2.12) : 3.2.14 -> 3.2.15
   org.scalatest:(scalatest, scalatest_2.12) : 3.2.14 -> 3.2.15
   org.wartremover:sbt-wartremover : 3.0.6 -> 3.0.9
   org.wartremover:(wartremover, wartremover_2.12.17) : 3.0.6 -> 3.0.9
   com.eed3si9n:sbt-assembly : 2.0.0 -> 2.1.0
   org.apache.spark:(spark-core, spark-core_2.12) : 3.2.2 -> 3.2.3
   org.apache.spark:(spark-sql, spark-sql_2.12) : 3.2.2 -> 3.2.3
   org.apache.spark:(spark-streaming, spark-streaming_2.12) : 3.2.2 -> 3.2.3
   org.scala-lang:scala-library : 2.12.17 -> 2.13.10
   org.scala-sbt:sbt : 1.7.2 -> 1.7.3
   org.scalameta:sbt-scalafmt : 2.4.5 -> 2.5.0
 2023-01-16 21:45:06,458 INFO  affinehealth/ProviderData is outdated:
   new version: io.netty:netty-all : 4.1.50.Final -> 4.1.87.Final
   new version: org.scalactic:(scalactic, scalactic_2.12) : 3.2.14 -> 3.2.15
   new version: org.scalatest:(scalatest, scalatest_2.12) : 3.2.14 -> 3.2.15
   new version: org.wartremover:(wartremover, wartremover_2.12.17) : 3.0.6 -> 3.0.9
   new version: org.wartremover:sbt-wartremover : 3.0.6 -> 3.0.9
 2023-01-16 21:45:06,461 INFO  Nurture affinehealth/ProviderData
 2023-01-16 21:45:06,467 INFO  Clone affinehealth/ProviderData
 2023-01-16 21:45:06,979 INFO  Found 4 updates:
   io.netty:netty-all : 4.1.50.Final -> 4.1.87.Final
   org.scalactic:(scalactic, scalactic_2.12) : 3.2.14 -> 3.2.15
   org.scalatest:(scalatest, scalatest_2.12) : 3.2.14 -> 3.2.15
   org.wartremover:{sbt-wartremover, (wartremover, wartremover_2.12.17)} : 3.0.6 -> 3.0.9
 2023-01-16 21:45:06,994 INFO  Process update io.netty:netty-all : 4.1.50.Final -> 4.1.87.Final
 2023-01-16 21:45:07,364 INFO  Create branch update/netty-all-4.1.87.Final
 2023-01-16 21:45:08,590 ERROR Steward affinehealth/ProviderData failed
 java.io.IOException: 'GIT_ASKPASS=/home/runner/scala-steward/askpass.sh "SBT_OPTS=-Xmx2048m -Xss8m -XX:MaxMetaspaceSize=512m" git -c core.hooksPath=/dev/null commit --all --gpg-sign -m Update netty-all to 4.1.87.Final' exited with code 128
 error: gpg failed to sign the data
 fatal: failed to write commit object
 
  at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:54)
  at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:50)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at modify @ fs2.internal.Scope.close(Scope.scala:262)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:157)
  at get @ fs2.internal.Scope.openScope(Scope.scala:281)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1209)
  at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
 2023-01-16 21:45:08,594 INFO  ──────────── Total time: Steward affinehealth/ProviderData: 4s 421ms ────────────
 2023-01-16 21:45:08,596 INFO  ──────────── Total time: run: 6s 264ms ────────────
✕ Launching scala-steward failed
```

Workflow
```yaml
name: Launch Scala Steward

# This workflow will run Scala Steward and determine if any dependencies need to be updated.
# Because we want all workflows to also run on PRs submitted by Scala Steward a Personal Access Token MUST be used.
# Beware that using the Personal Access Token will make it look like it's you who submitted all the PRs.
# The workaround for this is to create a separate GitHub account for the Action and give it the Collaborator
# permission in the repository or repositories you wish to update.

on:
  pull_request:
    paths:
      - "**.sbt"
      - ".github/workflows/scala-steward.yml"
  schedule:
    # This workflow will launch at 00:00 every Sunday
           # ┌───────────── minute (0 - 59)
           # │ ┌───────────── hour (0 - 23)
           # │ │ ┌───────────── day of the month (1 - 31)
           # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
           # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
           # │ │ │ │ │
           # │ │ │ │ │
           # │ │ │ │ │
           # * * * * *
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: sbt
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
          signing-key: ${{ steps.import_gpg.outputs.keyid }}
          sign-commits: true
          # By default, Scala Steward will use the email/name of the user that created the token added
          # in github-token, override that behavior and use author-email/author-name inputs from GPG key
          author-email: ${{ steps.import_gpg.outputs.email }}
          author-name:  ${{ steps.import_gpg.outputs.name }}
          # By default, Scala Steward will ignore "opts" files (such as .jvmopts or .sbtopts)
          # when found on repositories, to disable this feature set ignore-opts-files: false.
          # This is placed here with the default value as not to forget about it when
          # using (.jvmopts or .sbtopts)
          ignore-opts-files: true
```

Workflow
```yaml
name: Launch Scala Steward

# This workflow will run Scala Steward and determine if any dependencies need to be updated.
# Because we want all workflows to also run on PRs submitted by Scala Steward a Personal Access Token MUST be used.
# Beware that using the Personal Access Token will make it look like it's you who submitted all the PRs.
# The workaround for this is to create a separate GitHub account for the Action and give it the Collaborator
# permission in the repository or repositories you wish to update.

on:
  pull_request:
    paths:
      - "**.sbt"
      - ".github/workflows/scala-steward.yml"
  schedule:
    # This workflow will launch at 00:00 every Sunday
           # ┌───────────── minute (0 - 59)
           # │ ┌───────────── hour (0 - 23)
           # │ │ ┌───────────── day of the month (1 - 31)
           # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
           # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
           # │ │ │ │ │
           # │ │ │ │ │
           # │ │ │ │ │
           # * * * * *
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: sbt
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
          signing-key: ${{ steps.import_gpg.outputs.keyid }}
          sign-commits: true
          # By default, Scala Steward will use the email/name of the user that created the token added
          # in github-token, override that behavior and use author-email/author-name inputs from GPG key
          author-email: ${{ steps.import_gpg.outputs.email }}
          author-name:  ${{ steps.import_gpg.outputs.name }}
          # By default, Scala Steward will ignore "opts" files (such as .jvmopts or .sbtopts)
          # when found on repositories, to disable this feature set ignore-opts-files: false.
          # This is placed here with the default value as not to forget about it when
          # using (.jvmopts or .sbtopts)
          ignore-opts-files: true
```

**Comment by mzuehlke** [comment]
I don't know the action too well, but does this comment help: https://github.com/scala-steward-org/scala-steward/issues/758#issuecomment-1384898496

**Comment by egaxhaj** [comment]
The issue in that comment talks about not finding the keys. The action is finding and loading the keys. My issue is more related to 

> java.io.IOException: 'GIT_ASKPASS=/home/runner/scala-steward/askpass.sh "SBT_OPTS=-Xmx2048m -Xss8m -XX:MaxMetaspaceSize=512m" git -c core.hooksPath=/dev/null commit --all --gpg-sign -m Update netty-all to 4.1.87.Final' exited with code 128

My first guess is that it's not able to find `/home/runner/scala-steward/askpass.sh`.

**Comment by alejandrohdezma** [comment]
Hey @egaxhaj, sorry, I totally missed your issue in the action repository. Let me try reproducing it in a test repository, I'll come back with whatever I find.

**Comment by alejandrohdezma** [comment]
So I just tested it in this [test repository](https://github.com/alejandrohdezma/gpg-steward-test/blob/main/.github/workflows/scala-steward.yml) and everything is working as expected. The [run](https://github.com/alejandrohdezma/gpg-steward-test/actions/runs/4051904222) completed successfully and [created a couple PRs with the commits signed with my GPG key](https://github.com/alejandrohdezma/gpg-steward-test/pull/2). I followed the official guide in the action's README (see "Sign commits created by Scala Steward" in the [Guides](https://github.com/scala-steward-org/scala-steward-action/blob/master/README.md#guides) section). When I've issues like this in the past is usually a problem with the GPG key itself. You could verify if the GPG key is created correctly, and that the correct values are passed into the secrets used in the workflow.

**Comment by egaxhaj** [comment]
I followed the official instruction and I used my own keys which I already use for signing but got the same error. 

I'll take a look later into the week at the example repo and get back to you. Hopefully I find the issue.

**Comment by egaxhaj** [comment]
This has been fixed and can be closed. It was a type between the secret key name for the GPG key passphrase and the action :). It's surprising it did not fail in `ghaction-import-gpg` action and instead went on and failed the scala-steward action instead.
