### ISSUE TITLE
sbt not found with scala-steward-action

### ISSUE THREAD

**Issue by aleboulanger** [scala-steward-org/scala-steward#3227]
I tried to use the scala steward app with this workflow below but I have the error `cannot run program sbt`
```
on:
  workflow_dispatch:
name: Launch Scala Steward
jobs:
  scala-steward:
    runs-on: [self-hosted]
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-app-id: ${{ secrets.APP_ID }}
          github-app-installation-id: ${{ secrets.APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
```

```
  2023-11-30 14:54:32,099 ERROR Steward XXX/YYY failed
  java.io.IOException: Cannot run program "sbt" (in directory "/home/runner/scala-steward/workspace/repos/XXX/YYYY"): error=2, No such file or directory
  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
  	at org.scalasteward.core.io.process$.$anonfun$createProcess$2(process.scala:106)
  	at flatMap @ org.scalasteward.core.io.process$.createProcess(process.scala:104)
  	at flatMap @ org.scalasteward.core.io.process$.slurp(process.scala:62)
  	at delay @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.isDebugEnabled(Slf4jLoggerInternal.scala:65)
  	at ifM$extension @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.info(Slf4jLoggerInternal.scala:91)
  	at >>$extension @ org.scalasteward.core.io.ProcessAlg$.$anonfun$create$1(ProcessAlg.scala:92)
  	at main$ @ org.scalasteward.core.Main$.main(Main.scala:23)
  	at main$ @ org.scalasteward.core.Main$.main(Main.scala:23)
  Caused by: java.io.IOException: error=2, No such file or directory
  	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
  	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
  	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
  	at org.scalasteward.core.io.process$.$anonfun$createProcess$2(process.scala:106)
  	at cats.effect.unsafe.WorkerThread.blockOn(WorkerThread.scala:809)
  	at scala.concurrent.package$.blocking(package.scala:124)
  	at cats.effect.IOFiber.runLoop(IOFiber.scala:983)
  	at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1370)
  	at cats.effect.IOFiber.run(IOFiber.scala:113)
  	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:634)
```

I tried to add sbt using `actions/setup-java` but without any change for this error

**Comment by alejandrohdezma** [comment]
Hey @aleboulanger, since you seem to be using a self-hosted runner I would suggest you ensure SBT is both installed in the runner and accessible in the PATH before trying to execute the workflow. It seems one or the other (or both) are not true.
